### ISSUE TITLE
NPE when invoking RDF sample

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#1058]
**Description:**
Create a dataservice 
```
<data name="RDF" transports="http https local">
 <config enableOData="false" id="GetMoviebyGenre">
    <property name="rdf_datasource">/path/to/rdf/Movies.rdf</property>
 </config>
 <query id="GetMoviebyGenre" useConfig="GetMoviebyGenre">
    <sparql>
    <![CDATA[PREFIX cd: 
      <http://www.popular.movies/cd#>  SELECT ?title ?director ?year ?genre ?actorWHERE {        ?movie cd:title ?title.      ?movie cd:director ?director.      ?movie cd:year ?year.      ?movie cd:genre ?genre.      ?movie cd:actor ?actor.}]]></sparql>
      <result element="Movies" rowName="Movie">
         <element column="title" name="title" xsdType="string"/>
         <element column="director" name="director" xsdType="string"/>
         <element column="year" name="year" xsdType="string"/>
         <element column="genre" name="genre" xsdType="string"/>
         <element column="actor" name="actor" xsdType="string"/>
      </result>
      <param name="genre" sqlType="STRING"/>
   </query>
   <operation name="GetMoviesbyGenreOp">
      <call-query href="GetMoviebyGenre">
         <with-param name="genre" query-param="genre"/>
      </call-query>
   </operation>
   <resource method="GET" path="Movies/{genre}">
      <call-query href="GetMoviebyGenre">
         <with-param name="genre" query-param="genre"/>
      </call-query>
   </resource>
</data>
```

Invoke as,
`curl -X GET http://localhost:8290/services/RDF.HTTPEndpoint/Movies/Drama`

Getting following exception

ERROR {org.apache.synapse.transport.passthru.PassThroughHttpSender} - Failed to submit the response org.apache.axis2.AxisFault: DS Code: UNKNOWN_ERROR
Source Data Service:-
Name: RDF
Location: /RDF.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: GetMoviesbyGenreOp
Current Params: {genre=Drama}
Nested Exception:-
java.lang.NullPointerException

	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:78)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:626)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:285)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:45)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:444)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chanikag** [comment]
This is because of incorrect configuration.
sparql should be changed to
<![CDATA[PREFIX cd: 
      <http://www.popular.movies/cd#>  SELECT ?title ?director ?year ?genre ?actor WHERE {        ?movie cd:title ?title.      ?movie cd:director ?director.      ?movie cd:year ?year.      ?movie cd:genre ?genre.      ?movie cd:actor ?actor.}]]></sparql>
