### ISSUE TITLE
Error thrown when securevault.sh is run

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/micro-integrator#1060]
**Description:**
The following exception is thrown when securevault.sh is run as described in https://ei.docs.wso2.com/en/latest/micro-integrator/develop/creating-artifacts/encrypting-synapse-passwords/#encrypting-passwords-for-synapse-configurations
```
writing to: /home/user/temp/wso2mi-1.1.0/registry/config/repository/components/secure-vault/secure-vault.properties
org.wso2.micro.integrator.security.vault.SecureVaultException: Error loading properties from a file at : /home/user/temp/wso2mi-1.1.0/registry/config/repository/components/secure-vault/secure-vault.properties Error : /home/user/temp/wso2mi-1.1.0/registry/config/repository/components/secure-vault/secure-vault.properties (No such file or directory)
	at org.wso2.micro.integrator.security.vault.utils.Utils.writeKeyToFile(Utils.java:83)
	at org.wso2.micro.integrator.security.vault.VaultTool.main(VaultTool.java:69)
Caused by: java.io.FileNotFoundException: /home/user/temp/wso2mi-1.1.0/registry/config/repository/components/secure-vault/secure-vault.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.wso2.micro.integrator.security.vault.utils.Utils.writeKeyToFile(Utils.java:68)
	... 1 more
```

**Comment by sdkottegoda** [comment]
The issue can be overcome by manually creating the file `secure-vault.properties` inside `<MI_HOME>/registry/config/repository/components/secure-vault/` prior to executing securevault.sh
