### ISSUE TITLE
Load testing http request-response throws intermittent errors

### ISSUE THREAD

**Issue by niruhan** [wso2/micro-integrator#1064]
**Description:**
The objective was to load test WSO2 Stream Processor HTTP request-response at 3000 tps. We used MicroIntegrator as the back end to receive HTTP requests and just send a 500 error response. The Siddhi app used is as follows;

```
@App:name("reqresapp")
@App:description("This apps contains http req and res you which calls a mocky backend that returns 500 as status code")

@source(type='http', worker.count='20' ,receiver.url='http://0.0.0.0:5006/Sweetss', @map(type = 'json'))
define stream inputStream(echoed_no string);

@sink(type='http-request', sink.id='A1', publisher.url='http://localhost:8290/mocky', method='POST', headers="'Content-Type:application/json'", @map(type='json'))
define stream outputStream (echoed_no string);


@source(type='http-response',sink.id='A1',http.status.code='[2|5]00',@map(type ='json', @attributes(echoed_no = '$.status')))
define stream JSONinstream (echoed_no string);

@sink(type='log',@map(type='json'))
define stream JSONoutstream (echoed_no string);

@info(name='query1')
from inputStream
select *
insert into outputStream;

@info(name='query2')
from JSONinstream
select *
insert into JSONoutstream;
```

The xml file placed inside synapse-configs/default/api is as follows,
```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/mocky" name="MockyAPI" xmlns="http://ws.apache.org/ns/synapse">
<resource methods="POST">
    <inSequence>
        <property name="HTTP_SC" value="500" scope="axis2"/>
                     <payloadFactory media-type="json">
                        <format>{ "status": "ERROR!"}</format>
                        <args/>
        </payloadFactory>
        <respond/>
    </inSequence>
    <outSequence/>
    <faultSequence/>
</resource>
</api>
```

**Affected Product Version:**
wso2mi-1.1.0

**OS, DB, other environment details and versions:**    
MacOS Mojave 10.14.3, WSO2 Stream Processor 4.4.0

**Steps to reproduce:**
1. Start the microintegrator with the above xml added.
2. start WSO2 SP with the above siddhi app
3. Send the following json request to http://localhost:5006/Sweetss using jmeter with 1500 threads
```
{
 "event": {
   "echoed_no": "100"
 }
}
```

The following is the expected console print in SP. This should be printed repeatedly.
```
[2019-10-28 09:49:09,971]  INFO {org.wso2.siddhi.core.stream.output.sink.LogSink} - reqresapp : JSONoutstream : {"event":{"echoed_no":"ERROR!"}}
```

However, the following error messages appear intermittently.
```
[2019-10-28 09:49:09,837] ERROR {org.wso2.extension.siddhi.io.http.source.HttpResponseConnectorListener} - Error occurred during processing response for the request sent by http-request-sink with 'sink.id' = A1 in Siddhi app reqresapp. org.wso2.transport.http.netty.contract.ServerConnectorException: Remote host closed the connection before initiating inbound response
	at org.wso2.transport.http.netty.contractimpl.sender.states.RequestCompleted.handleAbruptChannelClosure(RequestCompleted.java:76)
	at org.wso2.transport.http.netty.contractimpl.sender.TargetHandler.channelInactive(TargetHandler.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at org.wso2.transport.http.netty.contractimpl.common.BackPressureHandler.channelInactive(BackPressureHandler.java:45)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.codec.http.HttpContentDecoder.channelInactive(HttpContentDecoder.java:205)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:420)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:282)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

[2019-10-28 09:49:09,842] ERROR {org.wso2.transport.http.netty.contractimpl.sender.states.RequestCompleted} - Remote host closed the connection before initiating inbound response
```

These errors do not appear when using a wiremock backend for load testing.

**Comment by Nirothipan** [comment]
Issue moved to [wso2/streaming-integrator #136](https://github.com/wso2/streaming-integrator/issues/136) via [**ZenHub**](https://www.zenhub.com/)
