### ISSUE TITLE
API deployment failed when using Integration Studio to unit test the Apis component in micro-integrator 1.1.0

### ISSUE THREAD

**Issue by eiyouwang** [wso2/micro-integrator#1083]
**Description:**
When using Integration studio to unit test an APIs component in MI 1.10, it shows error shown below:
[2019-11-27 16:52:46,480] ERROR {org.apache.synapse.unittest.TestingAgent} - API api_test deployment failed

FULL LOG:
[2019-11-27 16:52:46,173]  INFO {org.apache.synapse.unittest.UnitTestingExecutor} - Unit testing agent checks transport Pass-through HTTP Listener port
[2019-11-27 16:52:46,210]  INFO {org.apache.synapse.unittest.SynapseTestcaseDataReader} - Artifact data from descriptor data read successfully
[2019-11-27 16:52:46,212]  INFO {org.apache.synapse.unittest.SynapseTestcaseDataReader} - Test case data from descriptor data read successfully
[2019-11-27 16:52:46,213]  INFO {org.apache.synapse.unittest.SynapseTestcaseDataReader} - Mock service data from descriptor data read successfully
[2019-11-27 16:52:46,255]  INFO {org.apache.synapse.unittest.ConfigModifier} - Mock service creator ready to start service for endpoint
[2019-11-27 16:52:46,265]  INFO {org.apache.synapse.unittest.MockServiceCreator} - Mock service started for endpoint in - http://localhost:9190/endpoints
[2019-11-27 16:52:46,270]  INFO {org.apache.synapse.unittest.ConfigModifier} - Thread waiting for mock service(s) starting
[2019-11-27 16:52:46,366]  INFO {io.netty.handler.logging.LoggingHandler} - [id: 0x551908a8] REGISTERED
[2019-11-27 16:52:46,368]  INFO {io.netty.handler.logging.LoggingHandler} - [id: 0x551908a8] BIND(localhost/127.0.0.1:9190)
[2019-11-27 16:52:46,369]  INFO {org.apache.synapse.unittest.ConfigModifier} - Mock service(s) are started with given ports
[2019-11-27 16:52:46,370]  INFO {io.netty.handler.logging.LoggingHandler} - [id: 0x551908a8, L:/127.0.0.1:9190] ACTIVE
[2019-11-27 16:52:46,372]  INFO {org.apache.synapse.unittest.UnitTestingExecutor} - Supportive artifacts deployment started
[2019-11-27 16:52:46,378]  INFO {io.netty.handler.logging.LoggingHandler} - [id: 0x551908a8, L:/127.0.0.1:9190] RECEIVED: [id: 0xa18ab5c5, L:/127.0.0.1:9190 - R:/127.0.0.1:38143]
[2019-11-27 16:52:46,428]  INFO {org.apache.synapse.deployers.SequenceDeployer} - Sequence named 'sequence' has been deployed from file : sequence
[2019-11-27 16:52:46,428]  INFO {org.apache.synapse.unittest.TestingAgent} - sequence - sequence artifact deployed successfully
[2019-11-27 16:52:46,458]  INFO {org.apache.synapse.deployers.EndpointDeployer} - Endpoint named 'endpoint' has been deployed from file : endpoint
[2019-11-27 16:52:46,459]  INFO {org.apache.synapse.unittest.TestingAgent} - endpoint - endpoint artifact deployed successfully
[2019-11-27 16:52:46,459]  INFO {org.apache.synapse.unittest.UnitTestingExecutor} - Test artifact deployment started
[2019-11-27 16:52:46,474]  INFO {org.apache.synapse.rest.API} - Initializing API: api_test:v1.0
[2019-11-27 16:52:46,475]  INFO {API_LOGGER.api_test} - Initializing API: api_test:v1.0
[2019-11-27 16:52:46,475]  INFO {org.apache.synapse.core.axis2.Axis2SynapseEnvironment} - Continuation call is set to true
[2019-11-27 16:52:46,479]  INFO {org.apache.synapse.deployers.APIDeployer} - API named 'api_test:v1.0' has been deployed from file : api_test
**_[2019-11-27 16:52:46,480] ERROR {org.apache.synapse.unittest.TestingAgent} - API api_test deployment failed_**
[2019-11-27 16:52:46,480]  INFO {org.apache.synapse.deployers.SequenceDeployer} - Sequence named 'sequence' has been undeployed
[2019-11-27 16:52:46,481]  INFO {org.apache.synapse.deployers.EndpointDeployer} - Endpoint named 'endpoint' has been undeployed
[2019-11-27 16:52:46,481]  INFO {org.apache.synapse.unittest.TestingAgent} - Undeployed all the deployed test and supportive artifacts
[2019-11-27 16:52:46,487]  INFO {io.netty.handler.logging.LoggingHandler} - [id: 0x551908a8, L:/127.0.0.1:9190] UNREGISTERED
[2019-11-27 16:52:46,492]  INFO {org.apache.synapse.commons.emulator.core.Emulator} - Emulator shutdown successfully.......
[2019-11-27 16:52:46,492]  INFO {org.apache.synapse.unittest.UnitTestingExecutor} - End processing test-case handler

LOG IN integration studio
[INFO] Scanning for projects...
[INFO]                                                                        
[INFO] ------------------------------------------------------------------------
[INFO] Building api_test 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- wso2-esb-api-plugin:2.1.0:pom-gen (api) @ api_test ---
[INFO] Creating maven project for artifact api_test:1.0.0...
[INFO]       generating maven project...
[INFO]       copying resources...
[INFO]
[INFO] --- wso2-esb-sequence-plugin:2.1.0:pom-gen (sequence) @ api_test ---
[INFO] Creating maven project for artifact sequence:1.0.0...
[INFO]       generating maven project...
[INFO]       copying resources...
[INFO]
[INFO] --- wso2-esb-endpoint-plugin:2.1.0:pom-gen (endpoint) @ api_test ---
[INFO] Creating maven project for artifact endpoint:1.0.0...
[INFO]       generating maven project...
[INFO]       copying resources...
[INFO]
[INFO] --- synapse-unit-test-maven-plugin:5.2.10:synapse-unit-test (synapse-unit-test) @ api_test ---
[INFO] ------------------------------------------------------------------------
[INFO] U N I T - T E S T S
[INFO] ------------------------------------------------------------------------
[INFO] Detect 1 Synapse test case files to execute
[INFO]
[INFO] SynapseTestCaseFile C:\Users\yaomj1\IntegrationStudio\workspace6\api_test\test\suite_1.xml tested successfully
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] U N I T - T E S T  R E P O R T
[INFO] ------------------------------------------------------------------------
[INFO] Start Time: 2019-11-27 16:52:45
[INFO] Test Run Duration: 0 seconds
[INFO] Test Summary:
[INFO]
[INFO] Test Suite Name: suite_1.xml
[INFO] ==============================================
[INFO] Pass Test Cases: N/A
[INFO] Failure Test Cases: N/A
[INFO]
[INFO] +-------------------+----------------+---------------+---------------+
[INFO] |   TEST CASE       |   DEPLOYMENT   |   MEDIATION   |   ASSERTION   |
[INFO] +===================+================+===============+===============+
[INFO] | Test Case - Suite |    FAILED      |    SKIPPED    |    SKIPPED    |
[INFO] +-------------------+----------------+---------------+---------------+
[INFO]
[INFO] Failed Test Case(s):
[INFO] +-------------------+-------------------+--------------------------------------+
[INFO] |   TEST CASE       |   FAILURE STATE   |       EXCEPTION / ERROR MESSAGE      |
[INFO] +===================+===================+======================================+
[INFO] | Test Case - Suite |    DEPLOYMENT     | API api_test deployment failed       |
[INFO] +-------------------+-------------------+--------------------------------------+
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.017 s
[INFO] Finished at: 2019-11-27T16:52:46+08:00
[INFO] Final Memory: 13M/189M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wso2.maven:synapse-unit-test-maven-plugin:5.2.10:synapse-unit-test (synapse-unit-test) on project api_test: Exception occurred while running test cases Overall unit test failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
 

Suggested Labels:

Micro Integrator, APIs, Unit test, Bug, Documentation

Suggested Assignees:

Affected Product Version:
wso2mi-1.1.0

OS, DB, other environment details and versions:

Steps to reproduce:
Just a sample project to test the unit test function in Integration studio
https://github.com/eiyouwang/api_test

Related Issues:

**Comment by eiyouwang** [comment]
another issue is when you using a remote server to test the APIs, you have to restart the MI in remote sever. otherwise it will shows duplication error:
[2019-11-27 16:50:08,681] ERROR {org.apache.synapse.deployers.APIDeployer} - API deployment from the file : api_test : Failed. org.apache.synapse.SynapseException: Duplicate resource definition by the name: api_test:v1.0
	at org.apache.synapse.config.SynapseConfiguration.handleException(SynapseConfiguration.java:1670)
	at org.apache.synapse.config.SynapseConfiguration.addAPI(SynapseConfiguration.java:433)
	at org.apache.synapse.config.SynapseConfiguration.addAPI(SynapseConfiguration.java:414)
	at org.apache.synapse.deployers.APIDeployer.deploySynapseArtifact(APIDeployer.java:59)
	at org.apache.synapse.unittest.ConfigurationDeployer.deployApiArtifact(ConfigurationDeployer.java:133)
	at org.apache.synapse.unittest.TestingAgent.processTestArtifact(TestingAgent.java:130)
	at org.apache.synapse.unittest.RequestHandler.runTestingAgent(RequestHandler.java:192)
	at org.apache.synapse.unittest.RequestHandler.run(RequestHandler.java:76)
	at java.lang.Thread.run(Thread.java:745)

[2019-11-27 16:50:08,682] ERROR {org.apache.synapse.unittest.TestingAgent} - Artifact deployment failed org.apache.synapse.deployers.SynapseArtifactDeploymentException: API deployment from the file : api_test : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.handleSynapseArtifactDeploymentError(AbstractSynapseArtifactDeployer.java:480)
	at org.apache.synapse.deployers.APIDeployer.deploySynapseArtifact(APIDeployer.java:71)
	at org.apache.synapse.unittest.ConfigurationDeployer.deployApiArtifact(ConfigurationDeployer.java:133)
	at org.apache.synapse.unittest.TestingAgent.processTestArtifact(TestingAgent.java:130)
	at org.apache.synapse.unittest.RequestHandler.runTestingAgent(RequestHandler.java:192)
	at org.apache.synapse.unittest.RequestHandler.run(RequestHandler.java:76)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.synapse.SynapseException: Duplicate resource definition by the name: api_test:v1.0
	at org.apache.synapse.config.SynapseConfiguration.handleException(SynapseConfiguration.java:1670)
	at org.apache.synapse.config.SynapseConfiguration.addAPI(SynapseConfiguration.java:433)
	at org.apache.synapse.config.SynapseConfiguration.addAPI(SynapseConfiguration.java:414)
	at org.apache.synapse.deployers.APIDeployer.deploySynapseArtifact(APIDeployer.java:59)
	... 5 more

**Comment by sajithaliyanage** [comment]
@eiyouwang , Thanks for pointing out this issue. We will fix this in our next release. However, for the moment you can proceed with the Unit test without having the ` version="1.0"  ` and `version-type="context"` attributes in **api** artifact. Like as follows,

```xml
<api context="/apis" name="api_test"  xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="GET" uri-template="/get">
    .....
</api>
``` 

This will resolve your both issues mentioned in above.

**Comment by sajithaliyanage** [comment]
Fixed in - https://github.com/wso2/wso2-synapse/pull/1459
