### ISSUE TITLE
Secured proxy invocation fails

### ISSUE THREAD

**Issue by shazni** [wso2/micro-integrator#1092]
**Description:**
A secured proxy invocation fails with an exception.

**Affected Product Version:**
7.0.0

**Steps to reproduce:**
- Created a simple WSDL based proxy
- Create a registry resource project and resource with WS-Policy
- Enable a simple user name token scenario security policy
- Enable security of the created proxy with the created security policy
- Create CApp of the above project
- Deploy to the EI 7
- Invoke the proxy

The following exception is thrown.
```
[2019-12-10 14:32:38,852]  WARN {org.apache.ws.security.util.Loader} - org.wso2.carbon.security.util.SecurityTokenStore java.lang.ClassNotFoundException: org.wso2.carbon.security.util.SecurityTokenStore
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.osgi.internal.framework.ContextFinder.loadClass(ContextFinder.java:139)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.ws.security.util.Loader.loadClass(Loader.java:155)
	at org.apache.rampart.RampartMessageData.getTokenStorage(RampartMessageData.java:757)
	at org.apache.rampart.RampartEngine.process(RampartEngine.java:172)
	at org.apache.rampart.handler.RampartReceiver.invoke(RampartReceiver.java:93)
	at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
	at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:444)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2019-12-10 14:32:38,857]  WARN {org.apache.ws.security.util.Loader} - org.wso2.carbon.security.util.SecurityTokenStore java.lang.ClassNotFoundException: org.wso2.carbon.security.util.SecurityTokenStore
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.osgi.internal.framework.ContextFinder.loadClass(ContextFinder.java:139)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.ws.security.util.Loader.loadClass(Loader.java:185)
	at org.apache.ws.security.util.Loader.loadClass(Loader.java:163)
	at org.apache.rampart.RampartMessageData.getTokenStorage(RampartMessageData.java:757)
	at org.apache.rampart.RampartEngine.process(RampartEngine.java:172)
	at org.apache.rampart.handler.RampartReceiver.invoke(RampartReceiver.java:93)
	at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
	at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:444)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2019-12-10 14:32:38,858] ERROR {org.apache.synapse.transport.passthru.ServerWorker} - Error processing POST request for : /services/Calculator.CalculatorHttpSoap11Endpoint. Error detail: Undefined 'WSHandler: cannot load token storage class: org.wso2.carbon.security.util.SecurityTokenStore' resource property. java.lang.RuntimeException: Undefined 'WSHandler: cannot load token storage class: org.wso2.carbon.security.util.SecurityTokenStore' resource property
	at org.apache.rampart.RampartException.getMessage(RampartException.java:81)
	at org.apache.rampart.RampartException.<init>(RampartException.java:61)
	at org.apache.rampart.RampartException.<init>(RampartException.java:67)
	at org.apache.rampart.RampartMessageData.getTokenStorage(RampartMessageData.java:759)
	at org.apache.rampart.RampartEngine.process(RampartEngine.java:172)
	at org.apache.rampart.handler.RampartReceiver.invoke(RampartReceiver.java:93)
	at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
	at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:444)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sdkottegoda** [comment]
Related to https://github.com/wso2/micro-integrator/issues/486 and https://github.com/wso2/micro-integrator/issues/630

**Comment by chanikag** [comment]
@shazni you have to change the token store class to org.wso2.micro.integrator.security.extensions.SecurityTokenStore in the policy file.
It is mentioned in the doc [1]
[1] https://ei.docs.wso2.com/en/7.1.0/micro-integrator/develop/advanced-development/applying-security-to-a-proxy-service/
