### ISSUE TITLE
Can't login to Micro Integrator dashboard when DenableCorrelationLogs is set to true

### ISSUE THREAD

**Issue by orifux** [wso2/micro-integrator#1129]
**Description:**
Can't login to https://10.0.2.15:9743/dashboard/login when starting the Micro-Integrator with both -DenableManagementAPI and -DenableCorrelationLogs parameters set to true.
The following errors are throw:
1. an error message is throw to the login page ""unknown error occurred!"

![Screenshot from 2020-02-03 15-31-06](https://user-images.githubusercontent.com/31374749/73661666-1ab67480-46a3-11ea-8230-ed5680d0d29f.png)

2. an error message is throw to the carbon log:
ori@ori-VirtualBox:/usr/lib/wso2/wso2ei/7.0.1/micro-integrator/bin$ sudo sh launcher_micro-integrator.sh
```
[2020-02-03 14:50:24,900]  INFO {org.apache.synapse.deployers.EndpointDeployer} - Endpoint named 'PineValleyEndpoint' has been deployed from file : /usr/lib/wso2/wso2ei/7.0.1/micro-integrator/tmp/carbonapps/-1234/1580734224791HealthcareConfigProjectCompositeApplication_1.0.0.car/PineValleyEndpoint_1.0.0/PineValleyEndpoint-1.0.0.xml
[2020-02-03 14:50:24,932]  INFO {org.apache.synapse.deployers.EndpointDeployer} - Endpoint named 'GrandOakEndpoint' has been deployed from file : /usr/lib/wso2/wso2ei/7.0.1/micro-integrator/tmp/carbonapps/-1234/1580734224791HealthcareConfigProjectCompositeApplication_1.0.0.car/GrandOakEndpoint_1.0.0/GrandOakEndpoint-1.0.0.xml
[2020-02-03 14:50:25,325]  INFO {org.apache.synapse.rest.API} - Initializing API: HealthcareAPI
[2020-02-03 14:50:25,329]  INFO {API_LOGGER.HealthcareAPI} - Initializing API: HealthcareAPI
[2020-02-03 14:50:25,335]  INFO {org.apache.synapse.core.axis2.Axis2SynapseEnvironment} - Continuation call is set to true
[2020-02-03 14:50:25,358]  INFO {org.apache.synapse.deployers.APIDeployer} - API named 'HealthcareAPI' has been deployed from file : /usr/lib/wso2/wso2ei/7.0.1/micro-integrator/tmp/carbonapps/-1234/1580734224791HealthcareConfigProjectCompositeApplication_1.0.0.car/HealthcareAPI_1.0.0/HealthcareAPI-1.0.0.xml
[2020-02-03 14:50:25,365]  INFO {org.wso2.micro.integrator.initializer.deployment.application.deployer.CAppDeploymentManager} - Successfully Deployed Carbon Application : HealthcareConfigProjectCompositeApplication_1.0.0{super-tenant}
[2020-02-03 14:50:25,477]  INFO {org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager} - Pass-through HTTP Listener started on 0.0.0.0:8290
[2020-02-03 14:50:25,480]  INFO {org.apache.axis2.transport.mail.MailTransportListener} - MAILTO listener started
[2020-02-03 14:50:25,493]  INFO {org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager} - Pass-through HTTPS Listener started on 0.0.0.0:8253
[2020-02-03 14:50:25,497]  INFO {org.wso2.micro.integrator.initializer.StartupFinalizer} - WSO2 Micro Integrator started in 15 seconds
[2020-02-03 14:50:25,938]  WARN {org.wso2.micro.integrator.management.apis.ManagementInternalApi} - Micro Integrator Management REST API is enabled
[2020-02-03 14:50:26,333]  INFO {org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager} - Pass-through EI_INTERNAL_HTTPS_INBOUND_ENDPOINT Listener started on 0.0.0.0:9164
[2020-02-03 14:50:49,196] ERROR {org.apache.synapse.transport.passthru.SourceHandler} - Unexpected error: null java.lang.NullPointerException
	at org.apache.synapse.transport.passthru.SourceContext.updateState(SourceContext.java:183)
	at org.apache.synapse.transport.passthru.SourceHandler.getSourceRequest(SourceHandler.java:736)
	at org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpSourceHandler.requestReceived(InboundHttpSourceHandler.java:61)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:275)
	at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.consumeInput(LoggingNHttpServerConnection.java:114)
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onInputReady(MultiListenerServerIODispatch.java:83)
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onInputReady(MultiListenerServerIODispatch.java:32)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:218)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:281)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:748)

[2020-02-03 14:50:49,203] ERROR {org.apache.synapse.transport.passthru.SourceHandler} - Unexpected error: null java.lang.NullPointerException
	at org.apache.synapse.transport.passthru.SourceContext.updateState(SourceContext.java:183)
	at org.apache.synapse.transport.passthru.SourceHandler.exception(SourceHandler.java:603)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:298)
	at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.consumeInput(LoggingNHttpServerConnection.java:114)
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onInputReady(MultiListenerServerIODispatch.java:83)
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onInputReady(MultiListenerServerIODispatch.java:32)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:218)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:281)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:748)

[2020-02-03 14:50:49,213] ERROR {org.apache.synapse.transport.passthru.SourceHandler} - Unexpected error: null java.lang.NullPointerException
	at org.apache.synapse.transport.passthru.SourceContext.updateState(SourceContext.java:183)
	at org.apache.synapse.transport.passthru.SourceHandler.closed(SourceHandler.java:530)
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onClosed(MultiListenerServerIODispatch.java:61)
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onClosed(MultiListenerServerIODispatch.java:32)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.disconnected(AbstractIODispatch.java:100)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionClosed(BaseIOReactor.java:271)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processClosedSessions(AbstractIOReactor.java:439)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.hardShutdown(AbstractIOReactor.java:575)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:306)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:748)

[2020-02-03 14:50:50,215] FATAL {org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager} - Exception encountered in the HTTPS Listener. No more connections will be accepted by this transport org.apache.http.nio.reactor.IOReactorException: I/O dispatch worker terminated abnormally
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:357)
	at org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager$1.run(PassThroughListeningIOReactorManager.java:536)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.apache.synapse.transport.passthru.SourceContext.updateState(SourceContext.java:183)
	at org.apache.synapse.transport.passthru.SourceHandler.exception(SourceHandler.java:603)
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onClosed(MultiListenerServerIODispatch.java:63)
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onClosed(MultiListenerServerIODispatch.java:32)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.disconnected(AbstractIODispatch.java:100)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionClosed(BaseIOReactor.java:271)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processClosedSessions(AbstractIOReactor.java:439)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.hardShutdown(AbstractIOReactor.java:575)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:306)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	... 1 more

[2020-02-03 14:50:50,219]  INFO {org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager} - HTTPS Listener shutdown.
[2020-02-03 14:50:50,220]  INFO {org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager} - Shutting down shared IO Reactor
```

**Affected Product Version:**
micro-integrator 7.0.1

**Steps to reproduce:**
"-DenableCorrelationLogs" and "-DenableManagementApi" parameters set to "true" :
after the chage it shoul dbe like this:
....
#Start Product
su -c "env JAVA_HOME=${JAVA_HOME} bash $PRODUCT_HOME/bin/micro-integrator.sh -DenableCorrelationLogs=true -DenableManagementApi=true $@" wso2

2. Start the micro-integrator by runing the command:
        sudo sh launcher_micro-integrator.sh
3. Try to login to https://10.0.2.15:9743/dashboard or https://127.0.0.1:9743/dashboard with the user "admin" and password "admin"
You should get an error message

!!!! When i edited the Start Product line in launcher_micro-integrator.sh to have only the -DenableManagementApi without the -DenableCorrelationLogs
I have successfuly  login to the dashboard.

**Related Issues:**

**Comment by sdkottegoda** [comment]
Hi @orifux, Thank you for reporting the issue. We will look into this as soon as possible.

**Comment by Nirothipan** [comment]
This is happening as we can't enable correlation logs for inbound endpoints. Management API internally uses inbound endpoints and enabling correlation logs result in above error for inbound endpoints.

**Comment by sdkottegoda** [comment]
@Nirothipan let's fix https://github.com/wso2/micro-integrator/issues/1049 along with this.
