### ISSUE TITLE
Have to add a scenario replacing SecureProxy scenario for performance tests

### ISSUE THREAD

**Issue by Maninda** [wso2/micro-integrator#114]
[microeiisfailingatsecureproxyservices.zip](https://github.com/wso2/micro-integrator/files/3116472/microeiisfailingatsecureproxyservices.zip)

**Description:**
SecureProxy scenario is not supported in Micro EI. A supporting secure proxy scenario has to be implemented.

**Affected Product Version:**
Micro EI 6.4.0

**OS, DB, other environment details and versions:**    
Any environment

**Steps to reproduce:**
Try to invoke Performance Test scenario _SecureProxy_ in repo, "performance-ei" and the following exception could be observed.

`java.lang.RuntimeException: org.wso2.carbon.security.util.ServerCrypto Not Found
    at org.apache.ws.security.components.crypto.CryptoFactory.loadClass(CryptoFactory.java:203)
    at org.apache.ws.security.components.crypto.CryptoFactory.getInstance(CryptoFactory.java:95)
    at org.apache.rampart.util.RampartUtil.getSignatureCrypto(RampartUtil.java:390)
    at org.apache.rampart.RampartEngine.process(RampartEngine.java:166)
    at org.apache.rampart.handler.RampartReceiver.invoke(RampartReceiver.java:93)
    at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
    at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
    at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
    at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
    at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:415)
    at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
    at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)`

1. Deploy the attached CAR file in Micro EI and start.
2. Load the attached jmx script
3. In the HTTP Request section, set the file path of the attached XML file as the File Path of Files Upload tab
4. Once the request is sent above exception will happen.
5. When the issue is fixed the below exception will come as the backend service is unavailable.

[EI-Core]  WARN - ConnectCallback Connection refused or failed for : netty:8688

**Related Issues:**
[1] https://github.com/wso2/product-ei/issues/5600

**Comment by a5anka** [comment]
@Maninda Can you attach the proxy config and the related artifacts to the issue? It will help us to reproduce the issue.

**Comment by Maninda** [comment]
Edited the issue and attached artifacts and added the description to reproduce the exception.

**Comment by Maninda** [comment]
Edited the issue and attached artifacts and added the description to reproduce the exception.
