### ISSUE TITLE
[Management API] Cannot retrieve the list of available endpoints using management api

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/micro-integrator#1165]
**Description:**
The following exception occurs when trying to retrieve the list of available endpoints using management api by invoking [1].

```
[2020-02-21 15:18:31,254] ERROR {org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpServerWorker} - Exception occurred when running org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpServerWorker java.lang.NullPointerException
        at org.wso2.micro.integrator.management.apis.EndpointResource.populateEndpointList(EndpointResource.java:95)
        at org.wso2.micro.integrator.management.apis.EndpointResource.invoke(EndpointResource.java:66)
        at org.wso2.carbon.inbound.endpoint.internal.http.api.InternalAPIDispatcher.dispatch(InternalAPIDispatcher.java:86)
        at org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpServerWorker.run(InboundHttpServerWorker.java:109)
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

[1] - `curl -X GET "https://localhost:9164/management/endpoints" -H "accept: application/json" -H "Authorization: Bearer TOKEN" -k -i`

**Comment by Vathsan** [comment]
This issue happens only when a template endpoint is deployed.
