### ISSUE TITLE
[Salesforce REST Connector]Access token does not get refreshed automatically

### ISSUE THREAD

**Issue by isuruuy429** [wso2/micro-integrator#1206]
**Description:**
Even though it has been asked the refreshToken in the init method, the access token does not get refreshed using the refresh token. Therefore every time the user needs to manually get the tokens once they are expired. 

**Steps to reproduce:**
1. Obtain the client id, client secret, access token and refresh token from your Salesforce developer account. 
2. Set up the following API with the following configuration. 

retrive.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<sequence name="retrive" trace="disable" xmlns="http://ws.apache.org/ns/synapse">
    <property expression="json-eval($.sObject)" name="sObject" scope="default" type="STRING"/>
    <property expression="json-eval($.fieldAndValue)" name="fieldAndValue" scope="default" type="STRING"/>
    <salesforcerest.init>
        <accessToken></accessToken>
        <apiVersion>v44.0</apiVersion>
        <hostName>https://login.salesforce.com</hostName>
        <refreshToken></refreshToken>
        <clientSecret></clientSecret>
        <clientId></clientId>
        <apiUrl>https://ap16.salesforce.com</apiUrl>
        <registryPath>connectors/SalesforceRest</registryPath>
    </salesforcerest.init>
    <salesforcerest.query>
        <queryString>select id, name from Account</queryString>
    </salesforcerest.query>
</sequence>
```

create.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<sequence name="create" trace="disable" xmlns="http://ws.apache.org/ns/synapse">
    <property expression="json-eval($.sObject)" name="sObject" scope="default" type="STRING"/>
    <property expression="json-eval($.fieldAndValue)" name="fieldAndValue" scope="default" type="STRING"/>
    <salesforcerest.init>
        <accessToken></accessToken>
        <apiVersion>v44.0</apiVersion>
        <hostName>https://login.salesforce.com</hostName>
        <refreshToken></refreshToken>
        <clientSecret></clientSecret>
        <clientId></clientId>
        <apiUrl>https://ap16.salesforce.com</apiUrl>
        <registryPath>connectors/SalesforceRest</registryPath>
    </salesforcerest.init>
    <salesforcerest.create>
        <sObjectName>{$ctx:sObject}</sObjectName>
        <fieldAndValue>{$ctx:fieldAndValue}</fieldAndValue>
    </salesforcerest.create>
</sequence>
```

salesforcerest.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/salesforcerest" name="salesforcerest" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="POST">
        <inSequence>
            <sequence key="create"/>
            <sequence key="retrive"/>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```

3. Invoke the API with the following payload. 
```
{
	"sObject":"Account",
	"fieldAndValue": {
    "name": "Engineers",
    "description":"This Account belongs to WSO2"
  }
}
```

4. Keep the App inactive for 1 hour and invoke the API again. 
**Expected**: It should return the value. 
**Actual**: It will give you an error message

```
 ERROR {org.apache.axis2.description.ClientUtils} - The system cannot infer the transport information from the /services/data/v44.0/sobjects/Account URL.
[2020-03-10 13:09:25,926] ERROR {org.apache.synapse.core.axis2.Axis2Sender} - Unexpected error during sending message out org.apache.axis2.AxisFault: The system cannot infer the transport information from the /services/data/v44.0/sobjects/Account URL.
	at org.apache.axis2.description.ClientUtils.inferOutTransport(ClientUtils.java:86)
	at org.apache.synapse.core.axis2.DynamicAxisOperation$DynamicOperationClient.executeImpl(DynamicAxisOperation.java:116)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.synapse.core.axis2.Axis2FlexibleMEPClient.send(Axis2FlexibleMEPClient.java:634)
	at org.apache.synapse.core.axis2.Axis2Sender.sendOn(Axis2Sender.java:85)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:571)
	at org.apache.synapse.endpoints.AbstractEndpoint.send(AbstractEndpoint.java:408)
	at org.apache.synapse.endpoints.HTTPEndpoint.send(HTTPEndpoint.java:96)
	at org.apache.synapse.mediators.builtin.CallMediator.handleNonBlockingCall(CallMediator.java:278)
	at org.apache.synapse.mediators.builtin.CallMediator.mediate(CallMediator.java:122)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.config.xml.AnonymousListMediator.mediate(AnonymousListMediator.java:37)
	at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:205)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:133)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:148)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:84)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:281)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.mediateFromContinuationStateStack(Axis2SynapseEnvironment.java:807)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:305)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:578)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:195)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:284)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by skoneru** [comment]
Hi, Is someone able to get par this issue, if so, can you please post the solution. Thanks

**Comment by arunans23** [comment]
This issue is not reproducible in the latest connector version.
