### ISSUE TITLE
[Connectors] Fix DB event listener connector to be compatible with MI

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#1238]
**Description:**

When connector 1.0.3 version is setup with WSO2 MI it gives following error

```
[2020-01-24 17:47:34,386] ERROR {org.wso2.micro.integrator.ntask.core.impl.TaskQuartzJobAdapter} - Error in executing task: org/wso2/carbon/registry/api/RegistryException java.lang.NoClassDefFoundError: org/wso2/carbon/registry/api/RegistryException
at org.wso2.carbon.inbound.poll.dbeventlistener.DBEventPollingConsumer.fetchDataAndInject(DBEventPollingConsumer.java:178)
at org.wso2.carbon.inbound.poll.dbeventlistener.DBEventPollingConsumer.poll(DBEventPollingConsumer.java:347)
at org.wso2.carbon.inbound.endpoint.protocol.generic.GenericTask.taskExecute(GenericTask.java:40)
at org.wso2.carbon.inbound.endpoint.common.InboundTask.execute(InboundTask.java:43)
at org.wso2.micro.integrator.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:105)
at org.wso2.micro.integrator.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:63)
at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.registry.api.RegistryException cannot be found by org.apache.synapse.poll.dbeventlistener_1.0.2_1.0.0
at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 12 more
```

Need to fix the issue and release a new version of the connector.

**Comment by abeykoon** [comment]
This issue is fixed with the DB event listener v1.0.4
This should be fixed with commit: https://github.com/wso2-extensions/esb-inbound-dbevent/commit/4efada558305d38654b97b4e021013cae04da617
