### ISSUE TITLE
Certificate issue while trying to log in to the MI Monitoring Dashboard

### ISSUE THREAD

**Issue by Vathsan** [wso2/micro-integrator#1253]
**Description:**
When trying to login to MI Monitoring Dashboard with a self-signed certificate the following error occurs,

![image](https://user-images.githubusercontent.com/29911181/76856367-20de6a00-6879-11ea-830d-6b5eb75500fb.png)

We could observe the following logs in the dashboard console, 

```
ERROR {org.wso2.transport.http.netty.contractimpl.listener.WebSocketServerHandshakeHandler} - Error during WebSocket server handshake io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: bad_certificate
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

To overcome this issue we need to add the certificate of the micro integrator instance to the browser as a trusted source. We may direct the browser to `https://localhost:9164/management` and add the site as trusted (given MI hostname is localhost). Then we should be able to login to the MI dashboard with the host `localhost`. 
If we add the micro integrator instance to the browser as a trusted source by directing the browser to `https://{some_ip}:9164/management` then, the MI dashboard should be logged in with host `some_ip`.

**Comment by isudana** [comment]
This is what I get when I access https://{some_ip}:9164/management with Chrome in Mac OSX.


```
Your connection is not private
Attackers might be trying to steal your information from 192.168.1.240 (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_INVALID

Help improve Chrome security by sending URLs of some pages that you visit, limited system information and some page content to Google. Privacy Policy
192.168.1.240 normally uses encryption to protect your information. When Google Chrome tried to connect to 192.168.1.240 this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be 192.168.1.240, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit 192.168.1.240 at the moment because the website sent scrambled credentials that Google Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.
```

**Comment by isudana** [comment]
Can we fix it properly with a proper certificate?

**Comment by sdkottegoda** [comment]
We need to update the certificates in MI too
