### ISSUE TITLE
Generating error while consuming ISO8583 messages using the ISO8583 Inbound Endpoint

### ISSUE THREAD

**Issue by KasunAratthanage** [wso2/micro-integrator#1319]
**Description:**
Generating error while consuming ISO8583 messages using the ISO8583 Inbound Endpoint.

**Suggested Labels:**
ISO8583 Inbound Endpoint

**Affected Product Version:**
wso2mi-1.1.0

**OS, DB, other environment details and versions:**    
Ubuntu

**Steps to reproduce:**
1. Configure Micro integrator using following link.
https://github.com/wso2-extensions/esb-inbound-iso8583/blob/org.wso2.carbon.inbound.iso8583-1.0.1/docs/config.md

2. Create Inbound Endpoint and sequence.

**Inbound Endpoint**
```
<?xml version="1.0" encoding="UTF-8"?><inboundEndpoint xmlns="http://ws.apache.org/ns/synapse" name="custom_listener" sequence="requestISO" onError="fault" class="org.wso2.carbon.inbound.iso8583.listening.ISO8583MessageConsumer" suspend="false">
    <parameters>
        <parameter name="inbound.behavior">listening</parameter>
        <parameter name="sequential">true</parameter>
        <parameter name="coordination">true</parameter>
        <parameter name="port">5000</parameter>
        <parameter name="headerLength">2</parameter>
        <parameter name="isProxy">false</parameter>
    </parameters>
</inboundEndpoint>
```

**Sequence**

```
<?xml version="1.0" encoding="UTF-8"?>
<sequence name="requestISO" onError="fault" xmlns="http://ws.apache.org/ns/synapse">
    <log level="full">
        <property name="Log_Message for ISO8583 Inbound Endpoint" value="Message received from sample1-source"/>
    </log>
</sequence>
```

3. Setup and run TestClient program.
https://github.com/wso2-docs/CONNECTORS/tree/master/ISO8583/ISO8583TestClient/1.0.0

4. While listening to the ISO8583 messages getting following error.

```
Exception in thread "pool-13-thread-1" java.lang.NoClassDefFoundError: org/wso2/carbon/context/PrivilegedCarbonContext
	at org.wso2.carbon.inbound.iso8583.listening.ISO8583MessageInject.createMessageContext(ISO8583MessageInject.java:111)
	at org.wso2.carbon.inbound.iso8583.listening.ISO8583MessageInject.inject(ISO8583MessageInject.java:68)
	at org.wso2.carbon.inbound.iso8583.listening.ConnectionRequestHandler.connect(ConnectionRequestHandler.java:65)
	at org.wso2.carbon.inbound.iso8583.listening.ConnectionRequestHandler.run(ConnectionRequestHandler.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.context.PrivilegedCarbonContext cannot be found by org.wso2.carbon.inbound.iso8583_1.0.1_1.0.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

**Comment by gabrielnocce** [comment]
Good afternoon, have you been able to solve the problem? I have the same problem.
Thank you
