### ISSUE TITLE
Securevault fails in JDK11

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#1394]
**Description:**
$subject with following error. 
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at org.wso2.micro.integrator.security.vault.VaultTool.doEncryption(VaultTool.java:212)
	at org.wso2.micro.integrator.security.vault.VaultTool.encryptedValue(VaultTool.java:153)
	at org.wso2.micro.integrator.security.vault.VaultTool.main(VaultTool.java:60)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 3 more
```

**Comment by sachithKay** [comment]
As for the new implementation there is no need to execute the secure-vault.sh. All secrets are populated in the deployment.toml. Hence closing this issue.
