### ISSUE TITLE
Fix Github actions

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#1395]
**Description:**
GitHub actions are failing with failing error when running the all tests ( specially dss ).

```
2020-04-14T06:46:00.6966439Z [org.wso2.carbon.automation.engine.testlisteners.TestManagerListener] INFO : =================== On test success org.wso2.ei.dataservice.integration.test.services.ReturnUpdatedRowCountTestCase.performConcurrencyTest ===================
2020-04-14T06:46:05.9523329Z ##[error]Exception in thread "ThreadedStreamConsumer" java.lang.OutOfMemoryError: Java heap space
2020-04-14T06:46:05.9531460Z 	at java.util.Arrays.copyOf(Arrays.java:3332)
2020-04-14T06:46:05.9531781Z 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
2020-04-14T06:46:05.9532208Z 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
2020-04-14T06:46:05.9532595Z 	at java.lang.StringBuilder.append(StringBuilder.java:136)
2020-04-14T06:46:05.9532821Z 	at org.apache.maven.plugin.surefire.report.TestSetRunListener.getAsString(TestSetRunListener.java:223)
2020-04-14T06:46:05.9533229Z 	at org.apache.maven.plugin.surefire.report.TestSetRunListener.wrap(TestSetRunListener.java:230)
2020-04-14T06:46:05.9533470Z 	at org.apache.maven.plugin.surefire.report.TestSetRunListener.testSucceeded(TestSetRunListener.java:161)
2020-04-14T06:46:05.9533680Z 	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:100)
2020-04-14T06:46:05.9533914Z 	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:67)
2020-04-14T06:46:05.9534155Z 	at java.lang.Thread.run(Thread.java:748)
2020-04-14T06:47:36.1222914Z ##[error]Exception in thread "Thread-95" java.lang.OutOfMemoryError: Java heap space

```

**Comment by Nirothipan** [comment]
This issue is fixed. Hence closing .
