### ISSUE TITLE
[File Connector][readspecifiedLine]It always needs to provide the starting position as 1 or 0

### ISSUE THREAD

**Issue by isuruuy429** [wso2/micro-integrator#1483]
**Steps to reproduce:**
1. Create the following API in WSO2 Integration Studio. 
```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/file" name="File" xmlns="http://ws.apache.org/ns/synapse">
  <resource methods="POST" uri-template="/readRange">
        <inSequence>
            <property expression="json-eval($.source)" name="source" scope="default" type="STRING"/>
            <property expression="json-eval($.start)" name="start" scope="default" type="STRING"/>
            <property expression="json-eval($.end)" name="end" scope="default" type="STRING"/>
            <fileconnector.readSpecifiedLines>
                <source>{$ctx:source}</source>
                <contentType>application/json</contentType>
                <start>{$ctx:start}</start>
                <end>{$ctx:end}</end>
            </fileconnector.readSpecifiedLines>
            <log level="full"/>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```

2. Save the following JSON file as **payload.json**. 
```
{
  "aliceblue": [240, 248, 255, 1],
  "antiquewhite": [250, 235, 215, 1],
  "aqua": [0, 255, 255, 1],
  "aquamarine": [127, 255, 212, 1],
  "azure": [240, 255, 255, 1],
  "beige": [245, 245, 220, 1],
  "bisque": [255, 228, 196, 1],
  "black": [0, 0, 0, 1],
  "blanchedalmond": [255, 235, 205, 1],
  "blue": [0, 0, 255, 1],
  "blueviolet": [138, 43, 226, 1],
  "brown": [165, 42, 42, 1],
  "burlywood": [222, 184, 135, 1],
  "cadetblue": [95, 158, 160, 1],
  "chartreuse": [127, 255, 0, 1],
  "chocolate": [210, 105, 30, 1],
  "coral": [255, 127, 80, 1],
}
```

3. Invoke the API with the following payload. 
```
{
	"source":"/Users/IsuruUyanage/Desktop/jsonFiles/supun.json", 
	"start":"2",
	"end":"5"
}
```

Expected: It should provide the following lines in the output. 
```
  "antiquewhite": [
    250,
    235,
    215,
    1
  ],
  "aqua": [
    0,
    255,
    255,
    1
  ],
  "aquamarine": [
    127,
    255,
    212,
    1
  ],
```

Actual: It gives the following exception. 
```
[2020-04-27 11:52:37,135] ERROR {org.wso2.micro.integrator.core.json.JsonStreamBuilder} - Error occurred while processing document for application/json java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.micro.integrator.core.json.JsonStreamBuilder.processDocument(JsonStreamBuilder.java:69)
	at org.wso2.carbon.connector.util.ResultPayloadCreate.readSpecificLines(ResultPayloadCreate.java:267)
	at org.wso2.carbon.connector.ReadSpecifiedLines.connect(ReadSpecifiedLines.java:63)
	at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32)
	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:94)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:133)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:148)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:84)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:331)
	at org.apache.synapse.rest.API.process(API.java:440)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:135)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:113)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:325)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:412)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: #Can not parse stream. MessageID: urn:uuid:3521a964-891f-4a4d-9639-3b8b2f60db37. Error>>> #getNewJsonPayload. Could not save JSON payload. Invalid input stream found. Payload is not a JSON string.
	at org.apache.synapse.commons.json.JsonUtil.getNewJsonPayload(JsonUtil.java:752)
	at org.apache.synapse.commons.json.JsonStreamBuilder.processDocument(JsonStreamBuilder.java:43)
	... 31 more
Caused by: org.apache.axis2.AxisFault: #getNewJsonPayload. Could not save JSON payload. Invalid input stream found. Payload is not a JSON string.
	at org.apache.synapse.commons.json.JsonUtil.getNewJsonPayload(JsonUtil.java:736)
	... 32 more

[2020-04-27 11:52:37,161]  WARN {API_LOGGER.File} - Executing fault handler due to exception encountered
[2020-04-27 11:52:37,162]  WARN {API_LOGGER.File} - ERROR_CODE : 0 ERROR_MESSAGE : Error occured in the mediation of the class mediator
[2020-04-27 11:52:37,163]  WARN {API_LOGGER.File} - Executing fault sequence mediator : org.apache.synapse.mediators.base.SequenceMediator

````

**It outputs the range successfully only if we provide start as 0 or 1.**

**Comment by IvenYan** [comment]
I have the same error for the issue.How to fix the api or proxy?
![image](https://github.com/wso2/micro-integrator/assets/18438622/df3c88a3-4aa6-4079-a244-d578c0e63bde)
![image](https://github.com/wso2/micro-integrator/assets/18438622/1892933b-1075-44d0-b9f7-da82a89cd58e)
