### ISSUE TITLE
Data Services issue on Micro-Integrator with application/json

### ISSUE THREAD

**Issue by knightbeat** [wso2/micro-integrator#1496]
**Description:**

This is an issue with micro-integrator based data services.

The Query:
```
   <query id="select_with_key_orders_query" useConfig="default">
      <sql>SELECT order_id, sales_person, accept_mode, customer_id FROM orders WHERE order_id=?</sql>
      <result element="orders" rowName="order">
         <element column="order_id" name="order_id" xsdType="xs:string"/>
         <element column="sales_person" name="sales_person" xsdType="xs:string"/>
         <element column="accept_mode" name="accept_mode" xsdType="xs:string"/>
         <element column="customer_id" name="customer_id" xsdType="xs:string"/>
      </result>
      <param name="order_id" ordinal="1" sqlType="STRING"/>
   </query>
```

The Resource
```
   <resource method="GET" path="/orders/{order_id}">
      <call-query href="select_with_key_orders_query">
         <with-param name="order_id" query-param="order_id"/>
      </call-query>
   </resource>
```

When invoking with `application/xml` as the `Accept` header
```
GET https://{{dss-host}}:{{dss-port}}/services/ShopDatabaseService/orders
Accept: application/xml
```
Result is:
```
<orders xmlns="http://dss.shop-database.com">
  <order>
    <order_id>OR301</order_id>
    <sales_person>Jessey</sales_person>
    <accept_mode>Delivery</accept_mode>
    <customer_id>CU201</customer_id>
  </order>
  <order>
    <order_id>OR302</order_id>
    <sales_person>Mike</sales_person>
    <accept_mode>Delivery</accept_mode>
    <customer_id>CU207</customer_id>
  </order>
</orders>
```

When invoking with `application/json` as the `Accept` header
```
GET https://{{dss-host}}:{{dss-port}}/services/ShopDatabaseService/orders
Accept: application/json
```
Result is:
```
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=UTF-8
Date: Tue, 28 Apr 2020 16:27:10 GMT
Transfer-Encoding: chunked
Connection: close

{
  "Fault": {
    "faultcode": "soapenv:Server",
    "faultstring": "Failed to submit the response",
    "detail": ""
  }
}
```

Error on the console:
```
DS Code: DATABASE_ERROR
Source Data Service:-
Name: ShopDatabaseService
Location: /home/wso2carbon/wso2mi-1.1.0/tmp/carbonapps/-1234/1588088955253swiss-composite-01-1.0.0.car/ShopDatabaseService_1.0.0/ShopDatabaseService-1.0.0.dbs
Description: N/A
Default Namespace: http://dss.shop-database.com
Current Request Name: _get_orders
Current Params: {}
Nested Exception:-
java.lang.NullPointerException

	at org.wso2.micro.integrator.dataservices.core.description.query.SQLQuery.processPostNormalQuery(SQLQuery.java:854)
	at org.wso2.micro.integrator.dataservices.core.description.query.SQLQuery.runPostQuery(SQLQuery.java:2345)
	at org.wso2.micro.integrator.dataservices.core.description.query.Query.execute(Query.java:310)
	at org.wso2.micro.integrator.dataservices.core.engine.CallQuery.executeElement(CallQuery.java:280)
	at org.wso2.micro.integrator.dataservices.core.engine.OutputElement.execute(OutputElement.java:88)
	at org.wso2.micro.integrator.dataservices.core.description.resource.Resource.execute(Resource.java:66)
	at org.wso2.micro.integrator.dataservices.core.engine.DataService.invoke(DataService.java:596)
	at org.wso2.micro.integrator.dataservices.core.engine.DSOMDataSource.execute(DSOMDataSource.java:94)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.apache.axis2.json.gson.GsonXMLStreamWriter.skipChildElementsFromQueue(GsonXMLStreamWriter.java:399)
	at org.apache.axis2.json.gson.GsonXMLStreamWriter.writeStartElement(GsonXMLStreamWriter.java:272)
	at org.wso2.micro.integrator.dataservices.core.engine.XMLWriterHelper.writeResultElement(XMLWriterHelper.java:143)
	at org.wso2.micro.integrator.dataservices.core.engine.StaticOutputElement.executeElement(StaticOutputElement.java:262)
	at org.wso2.micro.integrator.dataservices.core.engine.OutputElement.execute(OutputElement.java:88)
	at org.wso2.micro.integrator.dataservices.core.engine.OutputElementGroup.executeElement(OutputElementGroup.java:105)
	at org.wso2.micro.integrator.dataservices.core.engine.OutputElement.execute(OutputElement.java:88)
	at org.wso2.micro.integrator.dataservices.core.description.query.Query.writeResultEntry(Query.java:443)
	at org.wso2.micro.integrator.dataservices.core.description.query.SQLQuery.processPostNormalQuery(SQLQuery.java:848)
	... 27 more

[2020-04-28 16:18:33,323] ERROR {org.apache.synapse.transport.passthru.PassThroughHttpSSLSender} - Failed to submit the response org.apache.axis2.AxisFault
	at org.wso2.micro.integrator.core.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:113)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:626)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:285)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:45)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:188)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2020-04-28 16:18:33,324] ERROR {org.apache.synapse.transport.passthru.ServerWorker} - Error processing GET request for : /services/ShopDatabaseService/orders org.apache.axis2.AxisFault: Failed to submit the response
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.handleException(PassThroughHttpSender.java:688)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:287)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:45)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:188)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault
	at org.wso2.micro.integrator.core.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:113)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:626)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:285)
	... 10 more
```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
micro-integrator:1.1.0

**OS, DB, other environment details and versions:**    
Docker image: `wso2/micro-integrator:1.1.0`
**Steps to reproduce:**

**Related Issues:**

**Comment by chanikag** [comment]
@knightbeat, I couldn't reproduce the reported issue. 
According to the configured resource, the order_id should be appended to the request URL. But in the two requests the order_id is not passed. Can you please check that, and if you are still facing the issue please post that with the dataservice config. 

This is the service I  used and I got expected results for both XML and JSON.
```
<data name="ShopDatabaseService" transports="http https local">
   <config enableOData="false" id="default">
      <property name="driverClassName">com.mysql.jdbc.Driver</property>
      <property name="url">jdbc:mysql://localhost:3306/mi</property>
      <property name="username">root</property>
      <property name="password">xxxxxxx</property>
   </config>
   <query id="query1" useConfig="default">
      <sql>SELECT order_id, sales_person, accept_mode, customer_id FROM orders WHERE order_id=?</sql>
      <result element="orders" rowName="order">
         <element column="order_id" name="order_id" xsdType="string"/>
         <element column="sales_person" name="sales_person" xsdType="string"/>
         <element column="accept_mode" name="accept_mode" xsdType="string"/>
         <element column="customer_id" name="customer_id" xsdType="string"/>
      </result>
      <param name="order_id" sqlType="STRING"/>
   </query>
   <resource method="GET" path="/orders/{order_id}">
      <call-query href="query1">
         <with-param name="order_id" query-param="order_id"/>
      </call-query>
   </resource>
</data>
```
In JSON builder we stream the payload unlike XML.
