### ISSUE TITLE
Getting java.lang.NoClassDefFoundError while executing the AmazonSQS Inbound Endpoint

### ISSUE THREAD

**Issue by KasunAratthanage** [wso2/micro-integrator#1565]
**Description:**
Getting java.lang.NoClassDefFoundError while executing the AmazonSQS Inbound Endpoint.

**Suggested Labels:**
AmazonSQS Inbound Endpoint

**Affected Product Version:**
wso2mi-1.1.0

**OS, DB, other environment details and versions:**    
Ubuntu

**Steps to reproduce:**
1. Clone [1] the repository and build the connector locally.
2. Add following Inbound endpoint and sequence.

**Inbound Endpoint**

```
<?xml version="1.0" encoding="UTF-8"?>
<inboundEndpoint class="org.wso2.carbon.inbound.amazonsqs.AmazonSQSPollingConsumer" name="AmazonSQS" onError="requestISO" sequence="request" suspend="false" xmlns="http://ws.apache.org/ns/synapse">
    <parameters>
        <parameter name="sequential">true</parameter>
        <parameter name="interval">2000</parameter>
        <parameter name="coordination">true</parameter>
        <parameter name="waitTime">19</parameter>
        <parameter name="maxNoOfMessage">10</parameter>
        <parameter name="destination">https://sqs.us-east-2.amazonaws.com/610968236798/eiconnectortestSQS</parameter>
        <parameter name="accessKey">AKIAY4Q</parameter>
        <parameter name="secretKey">SuQ4RsE/ZTf2H9Pg8qSUHWpdyaV1QhJ</parameter>
        <parameter name="attributeNames">attributeName1,contentType</parameter>
        <parameter name="contentType">text/plain</parameter>
        <parameter name="class">org.wso2.carbon.inbound.amazonsqs.AmazonSQSPollingConsumer</parameter>
        <parameter name="inbound.behavior">polling</parameter>
    </parameters>
</inboundEndpoint>
```

**Sequence**

```
<?xml version="1.0" encoding="UTF-8"?>
<sequence name="request" trace="disable" xmlns="http://ws.apache.org/ns/synapse">
    <log level="full"/>
</sequence>
```
3. Create a new Queue and insert data into newly created queue in the AmazonSQS.
4. While starting the Micro Integrator getting following error.

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[2020-05-20 12:56:10,908]  INFO {org.apache.synapse.inbound.InboundEndpoint} - Initializing Inbound Endpoint: AmazonSQS
[2020-05-20 12:56:10,941]  INFO {org.wso2.carbon.inbound.endpoint.protocol.generic.GenericProcessor} - Inbound listener AmazonSQS for class org.wso2.carbon.inbound.amazonsqs.AmazonSQSPollingConsumer starting ...
[2020-05-20 12:56:11,003] FATAL {org.wso2.micro.integrator.initializer.ServiceBusInitializer} - Failed to initialize ESB due to a fatal error java.lang.NoClassDefFoundError: com/amazonaws/AmazonServiceException
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.wso2.carbon.inbound.endpoint.protocol.generic.GenericProcessor.init(GenericProcessor.java:84)
	at org.apache.synapse.inbound.InboundEndpoint.init(InboundEndpoint.java:78)
	at org.apache.synapse.config.SynapseConfiguration.init(SynapseConfiguration.java:1571)
	at org.apache.synapse.Axis2SynapseController.createSynapseEnvironment(Axis2SynapseController.java:415)
	at org.apache.synapse.ServerManager.start(ServerManager.java:183)
	at org.wso2.micro.integrator.initializer.ServiceBusInitializer.initESB(ServiceBusInitializer.java:280)
	at org.wso2.micro.integrator.initializer.ServiceBusInitializer.activate(ServiceBusInitializer.java:134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.micro.integrator.ntask.core.internal.TasksDSComponent.activate(TasksDSComponent.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
	at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.AmazonServiceException cannot be found by org.apache.synapse.amazonsqs.poll.class_1.0.3_1.0.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 46 more
```

[1] https://github.com/wso2-extensions/esb-inbound-amazonsqs
[2] https://docs.wso2.com/display/ESBCONNECTORS/Configuring+AmazonSQS+Streaming+Inbound+Endpoint+Operations

**Comment by Nirothipan** [comment]
This class is not something we pack com.amazonaws.AmazonServiceException .. It should be coming from some external library. Could you check from where it is getting packed and add it as a lib and update.

**Comment by abeykoon** [comment]
@KasunAratthanage Could you please check adding the Jar file to droppings folder? In the documentation also we need to highlight that fact.

**Comment by KasunAratthanage** [comment]
After adding jar into droppings folder, it worked as expected manner.

**Comment by KasunAratthanage** [comment]
Closed this issue based on the above comment.

**Comment by KasunAratthanage** [comment]
Closed this issue based on the above comment.
