### ISSUE TITLE
DB-Report-Mediator not supported for the expression of 'json-eval'.

### ISSUE THREAD

**Issue by sanethmaduranga** [wso2/micro-integrator#1633]
**Description:**
The DB-Report-Mediator not supported for the expression of 'json-eval' When using the same it is returning the below error.

> [2020-06-04 17:21:10,562] ERROR {org.apache.synapse.config.xml.DBReportMediatorFactory} - Invalid XPath specified for the source attribute : json-eval($.username)
[2020-06-04 17:21:10,565]  WARN {org.apache.synapse.config.xml.SynapseXMLConfigurationFactory} - API configuration cannot be built - Continue in fail-safe mode org.apache.synapse.SynapseException: Invalid XPath specified for the source attribute : json-eval($.username)
	at org.apache.synapse.config.xml.AbstractMediatorFactory.handleException(AbstractMediatorFactory.java:215)
	at org.apache.synapse.config.xml.AbstractDBMediatorFactory.processStatements(AbstractDBMediatorFactory.java:337)
	at org.apache.synapse.config.xml.DBReportMediatorFactory.createSpecificMediator(DBReportMediatorFactory.java:79)
	at org.apache.synapse.config.xml.AbstractMediatorFactory.createMediator(AbstractMediatorFactory.java:96)
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:223)
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:46)
	at org.apache.synapse.config.xml.SequenceMediatorFactory.createAnonymousSequence(SequenceMediatorFactory.java:70)
	at org.apache.synapse.config.xml.rest.ResourceFactory.configureSequences(ResourceFactory.java:107)
	at org.apache.synapse.config.xml.rest.ResourceFactory.createResource(ResourceFactory.java:50)
	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:94)
	at org.apache.synapse.config.xml.SynapseXMLConfigurationFactory.defineAPI(SynapseXMLConfigurationFactory.java:437)
	at org.apache.synapse.config.xml.MultiXMLConfigurationBuilder.createAPIs(MultiXMLConfigurationBuilder.java:581)
	at org.apache.synapse.config.xml.MultiXMLConfigurationBuilder.getConfiguration(MultiXMLConfigurationBuilder.java:153)
	at org.apache.synapse.config.SynapseConfigurationBuilder.getConfiguration(SynapseConfigurationBuilder.java:107)
	at org.apache.synapse.Axis2SynapseController.createSynapseConfiguration(Axis2SynapseController.java:473)
	at org.wso2.micro.integrator.initializer.CarbonSynapseController.createSynapseConfiguration(CarbonSynapseController.java:162)
	at org.apache.synapse.ServerManager.start(ServerManager.java:179)
	at org.wso2.micro.integrator.initializer.ServiceBusInitializer.initESB(ServiceBusInitializer.java:280)
	at org.wso2.micro.integrator.initializer.ServiceBusInitializer.activate(ServiceBusInitializer.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.micro.integrator.ntask.core.internal.TasksDSComponent.activate(TasksDSComponent.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
	at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)

**Suggested Labels:**
MI-1.1.0 DB-Report-Mediator

**Comment by tishan89** [comment]
@GDLMadushanka Please send in the PR for DevStudio changes
