### ISSUE TITLE
Error in deploying RabbitMQ Inbound Endpoint

### ISSUE THREAD

**Issue by isuruuy429** [wso2/micro-integrator#1710]
**Description**
$subject and this issue does not appear in alpha pack. 

**Steps to reproduce:**
1. Do the following configurations in mi-home/conf/deployment.toml file as attached. 
2. Start the server and deploy the attached carbon application. 

**Expected**: Inbound Endpoint should be successfully deployed. 
**Actual**: Getting the following errors. 
```
[2020-06-17 19:15:14,562]  INFO {RabbitMQConnectionFactory} - [connection_factory] Successfully connected to RabbitMQ Broker
[2020-06-17 19:15:14,579] ERROR {RabbitMQConsumer} - Error occurred while initializing the consumer. java.io.IOException
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:129)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:125)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:147)
	at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:968)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.queueDeclare(AutorecoveringChannel.java:333)
	at org.wso2.carbon.inbound.endpoint.protocol.rabbitmq.RabbitMQUtils.declareQueue(RabbitMQUtils.java:204)
	at org.wso2.carbon.inbound.endpoint.protocol.rabbitmq.RabbitMQConsumer.initConsumer(RabbitMQConsumer.java:95)
	at org.wso2.carbon.inbound.endpoint.protocol.rabbitmq.RabbitMQConsumer.execute(RabbitMQConsumer.java:69)
	at org.wso2.carbon.inbound.endpoint.protocol.rabbitmq.RabbitMQTask.taskExecute(RabbitMQTask.java:43)
	at org.wso2.carbon.inbound.endpoint.common.OneTimeTriggerInboundTask.execute(OneTimeTriggerInboundTask.java:47)
	at org.wso2.micro.integrator.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:105)
	at org.wso2.micro.integrator.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:63)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'inbound' in vhost '/': received 'false' but current is 'true', class-id=50, method-id=10)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:293)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:141)
	... 15 more
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'inbound' in vhost '/': received 'false' but current is 'true', class-id=50, method-id=10)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:522)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:346)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:182)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:114)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:719)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:48)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:646)
	... 1 more

```

**Affected Product Version:**
- Pack : https://wso2.org/jenkins/job/products/job/micro-integrator/lastSuccessfulBuild/artifact/distribution/target/wso2mi-1.2.0-SNAPSHOT.zip

[rabbitmq-artifacts.zip](https://github.com/wso2/micro-integrator/files/4794669/rabbitmq-artifacts.zip)

**Comment by Nirothipan** [comment]
This should have been fixed with https://github.com/wso2/micro-integrator/pull/1690. Could you please try with latest pack from jenkins and update https://wso2.org/jenkins/job/products/job/micro-integrator/lastSuccessfulBuild/artifact/distribution/target/wso2mi-1.2.0-SNAPSHOT.zip

**Comment by isuruuy429** [comment]
Tested with the latest pack and getting the same issue.

**Comment by isuruuy429** [comment]
Tested in [661](https://wso2.org/jenkins/job/products/job/micro-integrator/661/) build. This is fixed.
