### ISSUE TITLE
Script mediator with registry reference throws exception when invoked

### ISSUE THREAD

**Issue by arunans23** [wso2/micro-integrator#175]
**Description:**

In micro-integrator, when a script mediator refers to a script in registry, it does not work and it throws an exception.

```
[2019-05-08 20:19:13,932] [micro-integrator] ERROR - ScriptMediator The script engine returned an Exception executing the external js script : Value {name ='null', keyValue ='gov:custom/checkJsScript.js'} function checkLog
java.lang.NullPointerException
	at org.wso2.carbon.mediation.registry.MicroIntegratorRegistry.lookUpFileMediaType(MicroIntegratorRegistry.java:983)
	at org.wso2.carbon.mediation.registry.MicroIntegratorRegistry.readNonXML(MicroIntegratorRegistry.java:816)
	at org.wso2.carbon.mediation.registry.MicroIntegratorRegistry.lookup(MicroIntegratorRegistry.java:203)
	at org.apache.synapse.registry.AbstractRegistry.getResource(AbstractRegistry.java:66)
	at org.apache.synapse.config.SynapseConfiguration.getEntry(SynapseConfiguration.java:867)
	at org.apache.synapse.core.axis2.Axis2MessageContext.getEntry(Axis2MessageContext.java:260)
	at org.apache.synapse.mediators.bsf.ScriptMediator.prepareExternalScript(ScriptMediator.java:486)
	at org.apache.synapse.mediators.bsf.ScriptMediator.mediateWithExternalScript(ScriptMediator.java:332)
	at org.apache.synapse.mediators.bsf.ScriptMediator.invokeScript(ScriptMediator.java:288)
	at org.apache.synapse.mediators.bsf.ScriptMediator.mediate(ScriptMediator.java:258)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:363)
	at org.apache.synapse.rest.API.process(API.java:431)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:135)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:113)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:325)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:92)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:338)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:383)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Artifacts used : 

**scriptTest.xml**
```
<api context="/check123" name="scriptTest" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="POST">
        <inSequence>
            <script function="checkLog" key="gov:custom/checkJsScript.js" language="js"/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```

**checkJsScript.js**

```
function checkLog(mc) {
	var log = mc.getServiceLog();        
	 log.info("Logging inside Script Mediator");
} 

```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by arunans23** [comment]
Since micro-integrator registry is different from WSO2 registry, it does not have all the metadata related to the registry files. In Script mediator, it requires a [DataHandler](https://github.com/wso2/wso2-synapse/blob/master/modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java#L494) which in turn requires [media type](https://github.com/wso2/carbon-mediation/blob/master/components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/WSO2Registry.java#L704) of the uploaded registry file. As a temporary fix, we need to map all the file extensions with Content-Type so that we can retrieve the media-type in runtime by looking at the file extension.

**Comment by arunans23** [comment]
After the changes, the registry functionalities of the following mediators were tested.

- [ ] Script mediator

- [ ] XSLT mediator

- [ ] Data mapper

**Comment by arunans23** [comment]
Currently a temporary fix is done to add all the file extension mapping in the code level. But a proper mechanism must be implemented to store the metadata of the registry files. Create a new issue to track the effort. #180
