### ISSUE TITLE
[External user store][Ldap][Management API]Get Users return 404

### ISSUE THREAD

**Issue by isuruuy429** [wso2/micro-integrator#1751]
**Description:**
When it is connected to an external user store (ldap), get users return 404. 
Doc: https://ei.docs.wso2.com/en/7.1.0/micro-integrator/administer-and-observe/working-with-management-api/#get-users

**Steps to reproduce:**
1. Create the following ldap user store. 
[userstore-ldif.zip](https://github.com/wso2/micro-integrator/files/4829475/userstore-ldif.zip)

2. Add the below configurations to the deployment.toml file. 
```
[internal_apis.file_user_store]
enable = false

[user_store]
type = "read_only_ldap"
class = "org.wso2.micro.integrator.security.user.core.ldap.ReadOnlyLDAPUserStoreManager"
connection_url = "ldap://localhost:10389"
connection_name = "uid=admin,ou=system"
connection_password = "secret"
user_search_base = "ou=system"
```

3. Start the micro integrator as below. 
`./micro-integrator.sh -DenableManagementApi`

4. Login to the server as below by obtaining the access token. 
```
curl -X GET "https://localhost:9164/management/login" -H "accept: application/json" -H "Authorization: Basic YWRtaW46c2VjcmV0" -k -i
```

5. Now try to invoke the users and add users as below. 
```
curl -X GET "https://localhost:9164/management/users?pattern=”*us*”&role=”role”" -H "accept: application/json" -H "Authorization: Bearer %AccessToken%" -k -i
```

```
curl -X POST -d @user "https://localhost:9164/management/users" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer %AccessToken% " -k -i
```
https://ei.docs.wso2.com/en/7.1.0/micro-integrator/administer-and-observe/working-with-management-api/#add-users

**Expected**: List the users or add users
**Actual**: Getting the following error. 

```
HTTP/1.1 404 Not Found
Authorization: Bearer eyJraWQiOiI0M2QyYzhiZi1mOTM0LTRhY2MtOWFkYS0xY2IxODJkZTdmZjYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlzcyI6Imh0dHBzOlwvXC8xMjcuMC4wLjE6OTE2NFwvIiwiZXhwIjoxNTkzMDcxNjAyfQ.WPza3dOJH5WAd0m9-oYSK1eysg72_YaBBk7L0XxPKA4cjLP2L0O08E0wHkqwW6CaJFbeX0rpodtq5YQSkFMRgLjhanrObT4ZMn0L5oGWcOQhvqb95goGn_WOqHZDt5yVLaXcaCRzyE-N_i1CK-5Y2uLAiW3hvMzlwqYpSu1dczoFGcvMkKxx_F3IFqeOu__zsOvag6QvX395SJ-Ll0-iKDXMej9OQKIycagtBtGJr5M68uKJ8XADLfJxb0YCvShh14p91bsp-a48y7Q0WA8cCgI2AW7BRRuk6JctfRMzRjx2XnuNk3dYUzBoNoGDePRciDTi1UhmW3LMuT_HrEbPyg
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE,OPTIONS, PATCH
Host: localhost:9164
Access-Control-Allow-Headers: Authorization, Content-Type
accept: application/json
Date: Thu, 25 Jun 2020 06:54:12 GMT
Transfer-Encoding: chunked

```

Carbon logs
```
[2020-06-25 12:24:12,488] ERROR {AbstractUserStoreManager} - Error occurred while accessing Java Security Manager Privilege Block when called by method getRoleListOfUser with 1 length of Objects and argTypes [class java.lang.String]
[2020-06-25 12:24:12,489] ERROR {AuthorizationHandler} - Error initializing the user store org.wso2.micro.integrator.security.user.core.UserStoreException: Error occurred while accessing Java Security Manager Privilege Block when called by method getRoleListOfUser with 1 length of Objects and argTypes [class java.lang.String]
	at org.wso2.micro.integrator.security.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:192)
	at org.wso2.micro.integrator.security.user.core.common.AbstractUserStoreManager.getRoleListOfUser(AbstractUserStoreManager.java:4271)
	at org.wso2.micro.integrator.management.apis.security.handler.AuthorizationHandler.authorize(AuthorizationHandler.java:109)
	at org.wso2.micro.integrator.management.apis.security.handler.AuthorizationHandler.processAuthorizationWithCarbonUserStore(AuthorizationHandler.java:99)
	at org.wso2.micro.integrator.management.apis.security.handler.AuthorizationHandler.authorize(AuthorizationHandler.java:79)
	at org.wso2.micro.integrator.management.apis.security.handler.AuthorizationHandlerAdapter.handle(AuthorizationHandlerAdapter.java:50)
	at org.wso2.micro.integrator.management.apis.security.handler.SecurityHandlerAdapter.invoke(SecurityHandlerAdapter.java:120)
	at org.wso2.micro.integrator.management.apis.security.handler.AuthorizationHandler.invoke(AuthorizationHandler.java:59)
	at org.wso2.carbon.inbound.endpoint.internal.http.api.InternalAPIDispatcher.dispatch(InternalAPIDispatcher.java:75)
	at org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpServerWorker.run(InboundHttpServerWorker.java:109)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.micro.integrator.security.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:171)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.micro.integrator.security.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:174)
	... 15 more
Caused by: java.lang.NullPointerException
	at org.wso2.micro.integrator.security.user.core.common.AbstractUserStoreManager.doGetInternalRoleListOfUser(AbstractUserStoreManager.java:386)
	at org.wso2.micro.integrator.security.user.core.common.AbstractUserStoreManager.doGetRoleListOfUser(AbstractUserStoreManager.java:5719)
	at org.wso2.micro.integrator.security.user.core.common.AbstractUserStoreManager.getRoleListOfUser(AbstractUserStoreManager.java:4295)
	... 20 more

[2020-06-25 12:24:12,490] ERROR {AuthorizationHandler} - User admin cannot be authorized


```
**Note**: 
But using the same above access token can access the resources such as apis, carbon applications, and etc. 
```
HTTP/1.1 200 OK
Authorization: Bearer eyJraWQiOiI0M2QyYzhiZi1mOTM0LTRhY2MtOWFkYS0xY2IxODJkZTdmZjYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlzcyI6Imh0dHBzOlwvXC8xMjcuMC4wLjE6OTE2NFwvIiwiZXhwIjoxNTkzMDcxNjAyfQ.WPza3dOJH5WAd0m9-oYSK1eysg72_YaBBk7L0XxPKA4cjLP2L0O08E0wHkqwW6CaJFbeX0rpodtq5YQSkFMRgLjhanrObT4ZMn0L5oGWcOQhvqb95goGn_WOqHZDt5yVLaXcaCRzyE-N_i1CK-5Y2uLAiW3hvMzlwqYpSu1dczoFGcvMkKxx_F3IFqeOu__zsOvag6QvX395SJ-Ll0-iKDXMej9OQKIycagtBtGJr5M68uKJ8XADLfJxb0YCvShh14p91bsp-a48y7Q0WA8cCgI2AW7BRRuk6JctfRMzRjx2XnuNk3dYUzBoNoGDePRciDTi1UhmW3LMuT_HrEbPyg
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE,OPTIONS, PATCH
Host: localhost:9164
Access-Control-Allow-Headers: Authorization, Content-Type
accept: application/json
Content-Type: application/json; charset=UTF-8
Date: Thu, 25 Jun 2020 06:55:40 GMT
Transfer-Encoding: chunked

{"count":2,"list":[{"name":"Extract","url":"http://localhost:8290/extract"},{"name":"TestGoogle","url":"http://localhost:8290/search"}]}%                                                                                                     

````

Further, invoking secured rest APIs too work with the existing users in the external user store.

**Comment by isuruuy429** [comment]
Tested this as below. 

1. Start WSO2 Identity Server. 
2. Add a user and assign the admin role to it. 
3. Add the following configurations to the deployment.toml file. 
```
[user_store]
type = "read_only_ldap"
connection_url = "ldap://localhost:10389"
connection_name = "uid=admin,ou=system"
connection_password = "admin"
user_search_base = "ou=Users,dc=wso2,dc=org"

[[management_api.authorization_handler.resources]]
path = "/user"

[management_api.cors]
enabled = true
allowed_origins = "https://localhost:9743,https://wso2.com:9743"
allowed_headers = "Authorization"

```

4. Repeat steps 3-5 in the above given discription. 

Output: 
```
HTTP/1.1 404 Not Found
Authorization: Bearer eyJraWQiOiIzYzNkNzY5Mi03MGZmLTQ4OWQtYTFlZi00NGNmYTIwMmIxNGEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlzcyI6Imh0dHBzOlwvXC8xMjcuMC4wLjE6OTE2NFwvIiwiZXhwIjoxNTkzMDkwODEzfQ.EGhbv6UNdhvG3ViFB0GmusA8xoEh0CW-2Z5Ljhfl9FZgRlZn6yt3tuP_TNUfMO9h6DQrcD56Oql6zuaku9wKjYb7NhabFi1DKpMIKRslD3Y_hYOQNYo_Gb4o022kAEqnT2TrA3p2hZ_K1RxcSH8J_kYgz0yNIOZMdsxnUfpeJjmpjXOv56TJiJcyurhA7OGR3OpqOd4Txt2C4rVwtIgKnn04ivC8MQ0PjhRkNPVSfwd9_fvdve00lLjzHfUGZ1800lljpcjtF4r-PC4tTWanoYFA6vJB8dBL-xzlp4hRRmavourvqaB9N8cKXT4V-PMAWE_gcGLtTi9YVsolpIz2vA
Access-Control-Allow-Methods: GET, POST, PUT, DELETE,OPTIONS, PATCH
Host: localhost:9164
Access-Control-Allow-Headers: Authorization
accept: application/json
Date: Thu, 25 Jun 2020 12:14:03 GMT
Transfer-Encoding: chunked
```

Carbon Log: 
`[2020-06-25 17:44:03,346] ERROR {AuthorizationHandler} - User admin cannot be authorized`

Tested this in patched pack. (Attached below)
[patch9999.zip](https://github.com/wso2/micro-integrator/files/4831102/patch9999.zip)
