### ISSUE TITLE
Ciphertool is not working properly with commented out values in deployment.toml

### ISSUE THREAD

**Issue by arunans23** [wso2/micro-integrator#1769]
**Description:**

With commented out values in deployment.toml, Ciphertool.sh is not working properly. It throws the following errors.

```
Encrypting using Internal KeyStore.
{type: JKS, alias: wso2carbon, path: /Users/user/wso2/micro-integrator/distribution/target/wso2mi-1.2.0-SNAPSHOT/repository/resources/security/wso2carbon.jks}

[Please Enter Internal KeyStore Password of Carbon Server : ]

Internal KeyStore of Carbon Server is initialized Successfully


Encryption is done Successfully

Exception in thread "main" java.lang.NullPointerException
	at java.lang.String.concat(String.java:2027)
	at org.wso2.ciphertool.CipherTool.updateDeploymentConfigurationWithEncryptedKeys(CipherTool.java:397)
	at org.wso2.ciphertool.CipherTool.main(CipherTool.java:75)
```

**Affected Product Version:**
1.2.0-SNAPSHOT

**Steps to reproduce:**

Use the below deployment.toml file. Run the ciphertool.sh. (With `-Dconfigure`)

```
[server]
hostname = "localhost"
# offset  = 10

[user_store]
type = "read_only_ldap"

[keystore.tls]
file_name = "wso2carbon.jks"
password = "$secret{secret_key}"
alias = "wso2carbon"
key_password = "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
password = "wso2carbon"
alias = "symmetric.key.value"
algorithm = "AES"

[secrets]
secret_key = "[wso2carbon]"

## Following are set of example configs. Please refer docs for complete set of configurations.

# [transport.http]
# socket_timeout = 180000   # timeout in milliseconds
# disable_connection_keepalive = false

# [transport.jms]
# sender_enable = true

# [[transport.jms.sender]]
# name = "myQueueSender"
# parameter.initial_naming_factory = "org.apache.activemq.jndi.ActiveMQInitialContextFactory"
# parameter.provider_url = "tcp://localhost:61616"
# parameter.connection_factory_name = "QueueConnectionFactory"
# parameter.connection_factory_type = "queue"
# parameter.cache_level = "producer"

# [transport.jms]
# listener_enable = true

#[[transport.jms.listener]]
# name = "myQueueConnectionFactory"
# parameter.initial_naming_factory = "org.apache.activemq.jndi.ActiveMQInitialContextFactory"
# parameter.provider_url = "tcp://localhost:61616"
# parameter.connection_factory_name = "QueueConnectionFactory"
# parameter.connection_factory_type = "queue"

# [transport.jndi.connection_factories]
# 'connectionfactory.QueueConnectionFactory' = "amqp://admin:admin@clientID/carbon?brokerlist='tcp://localhost:5675'"
# 'connectionfactory.TopicConnectionFactory' = "amqp://admin:admin@clientID/carbon?brokerlist='tcp://localhost:5675'"

# [transport.jndi.queue]
# jndiNameOfQueue = "physicalNameOfQueue"

# [transport.jndi.topic]
# jndiNameOfTopic = "physicalNameOfTopic"

# [transport.rabbitmq]
# sender_enable = true

# [[transport.rabbitmq.sender]]
# name = "AMQPConnectionFactory"
# parameter.hostname = "localhost"
# parameter.port = 5672
# parameter.username = "guest"
# parameter.password = "guest"

# [transport.rabbitmq]
# listener_enable = true

# [[transport.rabbitmq.listener]]
# name = "AMQPConnectionFactory"
# parameter.hostname = "localhost"
# parameter.port = 5672
# parameter.username = "guest"
# parameter.password = "guest"

# [system.parameter]
# 'key' = "value"

# [[datasource]]
# id = "WSO2CarbonDB"  # "WSO2_COORDINATION_DB"
# url = "jdbc:mysql://localhost:3306/integratordb"
# username = "root"
# password = "root"
# driver = "com.mysql.jdbc.Driver"

# [management_api]
# protocols = "http"

# [[internal_apis.users]]
# user.name = "user-1"
# user.password = "pwd-1"

# [transaction_counter]
# enable = true
# data_source = "WSO2CarbonDB"
# update_interval = 2

# [mediation]
# synapse.global_timeout_interval = "120000"  # interval in milliseconds

```

**Comment by Nirothipan** [comment]
I vaguely remember some issue like secrets sections have to be as last in the toml. Could you check if that is the issue .

**Comment by arunans23** [comment]
Related issue https://github.com/wso2/micro-integrator/issues/1106
