### ISSUE TITLE
Fix Intermittent test failure of AggregateWithHighMaxAndLowMinTestCase in actions.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#1777]
$subject. The above test is failing in actions intermittently with below stack trace.
Refer :https://github.com/wso2/wso2-synapse/pull/1566
```bash
2020-06-30T11:34:57.6167235Z Tests run: 494, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 951.804 sec <<< FAILURE!
2020-06-30T11:34:57.6167642Z testLessNumberThanMaximum(org.wso2.carbon.esb.mediator.test.aggregate.AggregateWithHighMaxAndLowMinTestCase)  Time elapsed: 45.198 sec  <<< FAILURE!
2020-06-30T11:34:57.6167865Z org.apache.axis2.AxisFault: Read timed out
2020-06-30T11:34:57.6167986Z 	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
2020-06-30T11:34:57.6168141Z 	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:227)
2020-06-30T11:34:57.6168321Z 	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:82)
2020-06-30T11:34:57.6168732Z 	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:459)
2020-06-30T11:34:57.6168888Z 	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:286)
2020-06-30T11:34:57.6169023Z 	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
2020-06-30T11:34:57.6169161Z 	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:442)
2020-06-30T11:34:57.6169298Z 	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228)
2020-06-30T11:34:57.6169430Z 	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
2020-06-30T11:34:57.6169567Z 	at org.wso2.esb.integration.common.utils.clients.axis2client.AxisOperationClient.send(AxisOperationClient.java:95)
2020-06-30T11:34:57.6169713Z 	at org.wso2.carbon.esb.mediator.test.aggregate.AggregatedRequestClient.getResponse(AggregatedRequestClient.java:54)
2020-06-30T11:34:57.6169858Z 	at org.wso2.carbon.esb.mediator.test.aggregate.AggregateWithHighMaxAndLowMinTestCase.testLessNumberThanMaximum(AggregateWithHighMaxAndLowMinTestCase.java:165)
2020-06-30T11:34:57.6170007Z Caused by: java.net.SocketTimeoutException: Read timed out
2020-06-30T11:34:57.6170132Z 	at java.net.SocketInputStream.socketRead0(Native Method)
2020-06-30T11:34:57.6170253Z 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
2020-06-30T11:34:57.6170496Z 	at java.net.SocketInputStream.read(SocketInputStream.java:171)
2020-06-30T11:34:57.6170619Z 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
2020-06-30T11:34:57.6170742Z 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
2020-06-30T11:34:57.6170865Z 	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
2020-06-30T11:34:57.6170995Z 	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
2020-06-30T11:34:57.6171135Z 	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
2020-06-30T11:34:57.6171254Z 	at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
2020-06-30T11:34:57.6171414Z 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
2020-06-30T11:34:57.6171572Z 	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
2020-06-30T11:34:57.6171717Z 	at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
2020-06-30T11:34:57.6171855Z 	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
2020-06-30T11:34:57.6171993Z 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
2020-06-30T11:34:57.6172136Z 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
2020-06-30T11:34:57.6172275Z 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
2020-06-30T11:34:57.6172417Z 	at org.apache.axis2.transport.http.AbstractHTTPSender.executeMethod(AbstractHTTPSender.java:712)
2020-06-30T11:34:57.6172555Z 	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:223)
2020-06-30T11:34:57.6172674Z 	... 44 more

```

**Comment by Nirothipan** [comment]
closing as this is not happening now
