### ISSUE TITLE
Carbondump.sh not working on Mac environment

### ISSUE THREAD

**Issue by arunans23** [wso2/micro-integrator#1838]
**Description:**

When you run the script to get the state of the system, the server gets killed and the files are empty in the generated dump.
https://docs.wso2.com/display/CLUSTER420/Troubleshooting+in+Production+Environments#TroubleshootinginProductionEnvironments-Capturingthestateofthesystem

It also generates the following error.
```
user@Users-MBP wso2mi-1.2.0-beta % sh bin/carbondump.sh -carbonHome /Users/user/mytmp/demo/wso2mi-1.2.0-beta -pid 1326
Java Version : 8

carbondump.sh##Generating the java memory dump...
Error attaching to process: sun.jvm.hotspot.debugger.DebuggerException: Can't attach symbolicator to the process
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerException: Can't attach symbolicator to the process
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$BsdDebuggerLocalWorkerThread.execute(BsdDebuggerLocal.java:169)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.attach(BsdDebuggerLocal.java:287)
	at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:671)
	at sun.jvm.hotspot.HotSpotAgent.setupDebuggerDarwin(HotSpotAgent.java:659)
	at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:341)
	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.PMap.main(PMap.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jmap.JMap.runTool(JMap.java:201)
	at sun.tools.jmap.JMap.main(JMap.java:130)
Caused by: sun.jvm.hotspot.debugger.DebuggerException: Can't attach symbolicator to the process
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.attach0(Native Method)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.access$100(BsdDebuggerLocal.java:65)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$1AttachTask.doit(BsdDebuggerLocal.java:278)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$BsdDebuggerLocalWorkerThread.run(BsdDebuggerLocal.java:144)

1326: No such process
1326: No such process
ERROR: attach: task_for_pid(1326) failed: '(os/kern) failure' (5)
Error attaching to process: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process. Could be caused by an incorrect pid or lack of privileges.
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process. Could be caused by an incorrect pid or lack of privileges.
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$BsdDebuggerLocalWorkerThread.execute(BsdDebuggerLocal.java:169)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.attach(BsdDebuggerLocal.java:287)
	at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:671)
	at sun.jvm.hotspot.HotSpotAgent.setupDebuggerDarwin(HotSpotAgent.java:659)
	at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:341)
	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.FinalizerInfo.main(FinalizerInfo.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jmap.JMap.runTool(JMap.java:201)
	at sun.tools.jmap.JMap.main(JMap.java:130)
Caused by: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process. Could be caused by an incorrect pid or lack of privileges.
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.attach0(Native Method)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.access$100(BsdDebuggerLocal.java:65)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$1AttachTask.doit(BsdDebuggerLocal.java:278)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$BsdDebuggerLocalWorkerThread.run(BsdDebuggerLocal.java:144)

ERROR: attach: task_for_pid(1326) failed: '(os/kern) failure' (5)
Error attaching to process: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process. Could be caused by an incorrect pid or lack of privileges.
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process. Could be caused by an incorrect pid or lack of privileges.
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$BsdDebuggerLocalWorkerThread.execute(BsdDebuggerLocal.java:169)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.attach(BsdDebuggerLocal.java:287)
	at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:671)
	at sun.jvm.hotspot.HotSpotAgent.setupDebuggerDarwin(HotSpotAgent.java:659)
	at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:341)
	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.HeapSummary.main(HeapSummary.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jmap.JMap.runTool(JMap.java:201)
	at sun.tools.jmap.JMap.main(JMap.java:130)
Caused by: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process. Could be caused by an incorrect pid or lack of privileges.
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.attach0(Native Method)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.access$100(BsdDebuggerLocal.java:65)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$1AttachTask.doit(BsdDebuggerLocal.java:278)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$BsdDebuggerLocalWorkerThread.run(BsdDebuggerLocal.java:144)

Java 8 or higher version
ERROR: attach: task_for_pid(1326) failed: '(os/kern) failure' (5)
Error attaching to process: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process. Could be caused by an incorrect pid or lack of privileges.
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process. Could be caused by an incorrect pid or lack of privileges.
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$BsdDebuggerLocalWorkerThread.execute(BsdDebuggerLocal.java:169)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.attach(BsdDebuggerLocal.java:287)
	at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:671)
	at sun.jvm.hotspot.HotSpotAgent.setupDebuggerDarwin(HotSpotAgent.java:659)
	at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:341)
	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.ClassLoaderStats.main(ClassLoaderStats.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jmap.JMap.runTool(JMap.java:201)
	at sun.tools.jmap.JMap.main(JMap.java:130)
Caused by: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process. Could be caused by an incorrect pid or lack of privileges.
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.attach0(Native Method)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.access$100(BsdDebuggerLocal.java:65)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$1AttachTask.doit(BsdDebuggerLocal.java:278)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal$BsdDebuggerLocalWorkerThread.run(BsdDebuggerLocal.java:144)


carbondump.sh##Generating the thread dump...
1326: No such process

carbondump.sh##Capturing OS information...
bin/carbondump.sh: line 199: lsmod: command not found
cat: /proc/meminfo: No such file or directory
cat: /proc/cpuinfo: No such file or directory
netstat: n: unknown or uninstrumented protocol
bin/carbondump.sh: line 206: dpkg: command not found
bin/carbondump.sh: line 207: rpm: command not found
bin/carbondump.sh: line 210: lsmod: command not found
bin/carbondump.sh: line 210: mawk: command not found

carbondump.sh##Capturing the list of running task in the system...
invalid option or syntax: -b
top usage: top
		[-a | -d | -e | -c <mode>]
		[-F | -f]
		[-h]
		[-i <interval>]
		[-l <samples>]
		[-ncols <columns>]
		[-o <key>] [-O <secondaryKey>]
			keys: pid (default), command, cpu, cpu_me, cpu_others, csw,
				time, threads, ports, mregion, mem, rprvt, purg, vsize, vprvt,
				kprvt, kshrd, pgrp, ppid, state, uid, wq, faults, cow, user,
				msgsent, msgrecv, sysbsd, sysmach, pageins, boosts, instrs, cycles
		[-R | -r]
		[-S]
		[-s <delay>]
		[-n <nprocs>]
		[-stats <key(s)>]
		[-pid <processid>]
		[-user <username>]
		[-U <username>]
		[-u]


carbondump.sh##Capturing OS Environment Variables...

carbondump.sh##Generating the checksums of all the files in the CARBON_HOME directory...
xargs: md5sum: No such file or directory
bin/carbondump.sh: line 228: mawk: command not found

carbondump.sh##Copying log files...

carbondump.sh##Copying conf files...

carbondump.sh##Copying database...

carbondump.sh##Getting a directory listing...

carbondump.sh##Compressing the carbondump...
  adding: carbondump-2020-07-13_13-51-39/ (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/memoryinfo/ (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/memoryinfo/java_heap_histogram.txt (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/memoryinfo/shared_object_mappings.txt (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/memoryinfo/java_heap_summary.txt (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/memoryinfo/objects_awaiting_finalization.txt (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/memoryinfo/java_clstats_statistics.txt (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/carbon_server_info.txt (deflated 31%)
  adding: carbondump-2020-07-13_13-51-39/thread_dump.txt (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/osinfo/ (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/osinfo/os_system_up_time.txt (deflated 49%)
  adding: carbondump-2020-07-13_13-51-39/osinfo/os_network_cards.txt (deflated 74%)
  adding: carbondump-2020-07-13_13-51-39/osinfo/os_meminfo.txt (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/osinfo/os_module_info.txt (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/osinfo/os_cpuinfo.txt (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/osinfo/os_module_list.txt (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/osinfo/os_installed_software_redhat_fedora.txt (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/osinfo/os_installed_software_unix_linux.txt (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/osinfo/os_env_variables.txt (deflated 41%)
  adding: carbondump-2020-07-13_13-51-39/osinfo/os_open_ports.txt (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/osinfo/os_running_tasks.txt (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/ (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/database/ (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/database/WSO2SHARED_DB.mv.db (deflated 86%)
  adding: carbondump-2020-07-13_13-51-39/repository/database/WSO2CARBON_DB.mv.db (deflated 86%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/ (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/tm-07-12-2020.out (deflated 26%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/wso2carbon-07-12-2020.log (deflated 79%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/wso2error.log (deflated 92%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/wso2carbon-07-09-2020.log (deflated 93%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/tm-07-09-2020.out (deflated 95%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/http_access_2020-07-09.log (deflated 98%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/correlation.log (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/wso2-mi-service.log (deflated 90%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/wso2error-07-10-2020.log (deflated 94%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/wso2error-07-09-2020.log (deflated 95%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/wso2carbon.log (deflated 90%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/audit.log (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/tm.out (deflated 91%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/wso2carbon-07-10-2020.log (deflated 93%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/wso2carbon-07-11-2020.log (deflated 93%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/http_access_2020-07-10.log (deflated 95%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/wso2-mi-api.log (deflated 89%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/http_access_2020-07-11.log (deflated 94%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/patches.log (deflated 95%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/tm-07-11-2020.out (deflated 94%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/tm-07-10-2020.out (deflated 95%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/wso2carbon-trace-messages.log (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/patches.log.lck (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/logs/http_access_.log (deflated 93%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/ (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/datasources/ (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/datasources/master-datasources.xml (deflated 75%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/user-mgt.xml (deflated 67%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/axis2/ (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/axis2/axis2_client.xml (deflated 79%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/axis2/axis2.xml (deflated 82%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/axis2/axis2_blocking_client.xml (deflated 78%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/deployment.toml.container (deflated 47%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/carbon.xml (deflated 70%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/security/ (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/security/authenticators.xml (deflated 66%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/security/xss-patterns.properties (deflated 54%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/security/cipher-tool.properties (deflated 54%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/security/cipher-text.properties (deflated 31%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/security/secret-conf.properties (deflated 69%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/security/Owasp.CsrfGuard.Carbon.properties (deflated 69%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/file.properties (deflated 39%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/etc/ (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/etc/logging-bridge.properties (deflated 66%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/etc/launch.ini (deflated 72%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/etc/carboncontext-osgi-services.properties (deflated 42%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/etc/osgi-debug.options (deflated 71%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/etc/mime.types (deflated 70%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/etc/mime.mappings (deflated 48%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/etc/config-validation.xml (deflated 67%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/etc/pax-logging.properties (deflated 13%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/etc/bundle-config/ (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/etc/jmx.xml (deflated 51%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/README (deflated 61%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/wso2-log-masking.properties (deflated 45%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/data-bridge/ (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/data-bridge/data-agent-config.xml (deflated 74%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/internal-apis.xml (deflated 67%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/datasources.properties (deflated 69%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/passthru-http.properties (deflated 47%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/access-log.properties (deflated 48%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/cipher-standalone-config.properties (deflated 52%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/deployment.toml (deflated 68%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/jndi.properties (deflated 46%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/log4j2.properties (deflated 82%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/carbon.properties (deflated 43%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/email/ (stored 0%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/email/email-admin-config.xml (deflated 46%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/synapse-handlers.xml (deflated 37%)
  adding: carbondump-2020-07-13_13-51-39/repository/conf/synapse.properties (deflated 54%)
  adding: carbondump-2020-07-13_13-51-39/directory_listing.txt (deflated 92%)
  adding: carbondump-2020-07-13_13-51-39/checksum_values.txt (stored 0%)

carbondump: /Users/user/mytmp/demo/wso2mi-1.2.0-beta/carbondump-2020-07-13_13-51-39.zip
```

**Affected Product Version:**
MI 1.2.0-beta

**Comment by Vathsan** [comment]
This does not happen in JDK 11. Please refer https://bugs.openjdk.java.net/browse/JDK-8160376
