### ISSUE TITLE
RabbitMQ issue in long running artifacts

### ISSUE THREAD

**Issue by isuruuy429** [wso2/micro-integrator#1860]
**Description:**
Encountered the following issue in long-running RabbitMQ Message Store tests. 

```
[2020-07-07 20:16:44,318] ERROR {org.apache.synapse.message.store.impl.rabbitmq.RabbitMQConsumer} - [RabbitMQMS-C-1] connection error when receiving messages. java.io.StreamCorruptedException: invalid stream header: 68656C6C
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:911)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:350)
	at org.apache.synapse.message.store.impl.rabbitmq.RabbitMQConsumer.deserializeMessage(RabbitMQConsumer.java:112)
	at org.apache.synapse.message.store.impl.rabbitmq.RabbitMQConsumer.receive(RabbitMQConsumer.java:72)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.fetch(ForwardingService.java:452)
	at org.apache.synapse.message.processor.impl.forwarder.ForwardingService.execute(ForwardingService.java:230)
	at org.wso2.micro.integrator.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:105)
	at org.wso2.micro.integrator.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:63)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by sdkottegoda** [comment]
When I convert the hex '68656C6C', it turns out to be 'hell' which is most probably a test message starting from 'hello' and the message published to the store in the test suite is 'Sending a message to RabbitMQ Store.'. Hence this is most probably due to a message that was published to the queue in some other way than the message store.

Message processor can only process messages added to the queue via the store, hence we will close this assuming that a message has been published in an undesired way.
