### ISSUE TITLE
RDF not working when the jdk minor version is greater than 255

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#1911]
**Description:**
It gives following error,

ERROR {NativeWorkerPool} - Uncaught exception java.lang.ExceptionInInitializerError
at com.ibm.icu.impl.UPropertyAliases.<clinit>(UPropertyAliases.java:88)
at com.ibm.icu.lang.UCharacter.<clinit>(UCharacter.java:5892)
at com.hp.hpl.jena.rdf.arp.impl.CharacterModel.isComposingChar(CharacterModel.java:134)
at com.hp.hpl.jena.rdf.arp.impl.ParserSupport.checkComposingChar(ParserSupport.java:140)
at com.hp.hpl.jena.rdf.arp.states.AbsWantLiteralValueOrDescription.characters(AbsWantLiteralValueOrDescription.java:46)
at com.hp.hpl.jena.rdf.arp.states.WantLiteralValueOrDescription.characters(WantLiteralValueOrDescription.java:65)
at com.hp.hpl.jena.rdf.arp.impl.XMLHandler.characters(XMLHandler.java:163)
at org.apache.xerces.parsers.AbstractSAXParser.characters(Unknown Source)
at org.apache.xerces.impl.XMLNamespaceBinder.characters(Unknown Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanContent(Unknown Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
at com.hp.hpl.jena.rdf.arp.impl.RDFXMLParser.parse(RDFXMLParser.java:107)
at com.hp.hpl.jena.rdf.arp.JenaReader.read(JenaReader.java:158)
at com.hp.hpl.jena.rdf.arp.JenaReader.read(JenaReader.java:145)
at com.hp.hpl.jena.rdf.arp.JenaReader.read(JenaReader.java:215)
at com.hp.hpl.jena.rdf.model.impl.ModelCom.read(ModelCom.java:191)
at org.wso2.micro.integrator.dataservices.core.description.config.RDFConfig.createRDFModel(RDFConfig.java:49)
at org.wso2.micro.integrator.dataservices.core.description.query.RdfFileQuery.getQueryExecution(RdfFileQuery.java:69)
at org.wso2.micro.integrator.dataservices.core.description.query.RdfFileQuery.processPreQuery(RdfFileQuery.java:82)
at org.wso2.micro.integrator.dataservices.core.description.query.SparqlQueryBase.runPreQuery(SparqlQueryBase.java:60)
at org.wso2.micro.integrator.dataservices.core.description.query.Query.execute(Query.java:301)
at org.wso2.micro.integrator.dataservices.core.engine.CallQuery.executeElement(CallQuery.java:280)
at org.wso2.micro.integrator.dataservices.core.engine.OutputElement.execute(OutputElement.java:88)
at org.wso2.micro.integrator.dataservices.core.description.operation.Operation.execute(Operation.java:56)
at org.wso2.micro.integrator.dataservices.core.engine.DataService.invoke(DataService.java:613)
at org.wso2.micro.integrator.dataservices.core.engine.DSOMDataSource.execute(DSOMDataSource.java:94)
at org.wso2.micro.integrator.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:72)
2020-07-21T14:11:41.7731307Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.micro.integrator.dataservices.core.dispatch.DataServiceRequest.dispatch(DataServiceRequest.java:358)
2020-07-21T14:11:41.7734359Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.micro.integrator.dataservices.core.DataServiceProcessor.dispatch(DataServiceProcessor.java:40)
2020-07-21T14:11:41.7737416Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.micro.integrator.dataservices.core.DBInOutMessageReceiver.invokeBusinessLogic(DBInOutMessageReceiver.java:81)
2020-07-21T14:11:41.7740570Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:42)
2020-07-21T14:11:41.7743017Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
2020-07-21T14:11:41.7745601Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
2020-07-21T14:11:41.7748120Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:458)
2020-07-21T14:11:41.7750513Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181)
2020-07-21T14:11:41.7752898Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
2020-07-21T14:11:41.7755359Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-07-21T14:11:41.7758032Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-07-21T14:11:41.7760809Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.lang.Thread.run(Thread.java:748)
2020-07-21T14:11:41.7763499Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Caused by: java.lang.IllegalArgumentException: Invalid version number: Version number may be negative or greater than 255
2020-07-21T14:11:41.7767325Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.ibm.icu.util.VersionInfo.getInstance(VersionInfo.java:191)
2020-07-21T14:11:41.7770116Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.ibm.icu.impl.ICUDebug.getInstanceLenient(ICUDebug.java:65)
2020-07-21T14:11:41.7773875Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.ibm.icu.impl.ICUDebug.<clinit>(ICUDebug.java:69)
2020-07-21T14:11:41.7776477Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	... 44 more
2020-07-21T14:11:41.7778856Z INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 
2020-07-21

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tishan89** [comment]
- RDF is a rarely used protocol
- There is a work around to change jdk version too
Hence ROI of engineering effort to solve this is low. Hence closing the issue
