### ISSUE TITLE
Exception at server startup after enabling the JMS sender and listener

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/micro-integrator#1934]
**Description:**
- Uncomment https://github.com/wso2/micro-integrator/blob/master/distribution/src/conf/deployment.toml#L27-L46
- The server startup will end up with the following exception
```sh
indika@indikas:~/Downloads/wso2mi-1.2.0/bin$ ./micro-integrator.sh 
[2020-07-31 14:10:54,073]  WARN {org.wso2.config.mapper.ConfigParser} - Overriding files in configuration directory /home/indika/Downloads/wso2mi-1.2.0
[2020-07-31 14:10:54,175] ERROR {org.wso2.config.mapper.TomlParser} - transport.jms previously defined at line 27, column 1 (line 38, column 1)
[2020-07-31 14:10:54,176] FATAL {org.wso2.micro.integrator.server.Main} - Error while performing configuration changes
org.wso2.config.mapper.ConfigParserException: Error parsing deployment configuration
	at org.wso2.config.mapper.TomlParser.parse(TomlParser.java:140) ~[config-mapper-1.0.12.jar:1.0.12]
	at org.wso2.config.mapper.ConfigParser.parse(ConfigParser.java:260) ~[config-mapper-1.0.12.jar:1.0.12]
	at org.wso2.config.mapper.ConfigParser.deploy(ConfigParser.java:228) ~[config-mapper-1.0.12.jar:1.0.12]
	at org.wso2.config.mapper.ConfigParser.deployAndStoreMetadata(ConfigParser.java:189) ~[config-mapper-1.0.12.jar:1.0.12]
	at org.wso2.config.mapper.ConfigParser.parse(ConfigParser.java:137) ~[config-mapper-1.0.12.jar:1.0.12]
	at org.wso2.micro.integrator.server.Main.handleConfiguration(Main.java:363) [org.wso2.micro.integrator.server-1.2.0.jar:1.2.0]
	at org.wso2.micro.integrator.server.Main.main(Main.java:105) [org.wso2.micro.integrator.server-1.2.0.jar:1.2.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_241]
	at org.wso2.micro.integrator.bootstrap.Bootstrap.loadClass(Bootstrap.java:70) [org.wso2.micro.integrator.bootstrap-1.2.0.jar:1.2.0]
	at org.wso2.micro.integrator.bootstrap.Bootstrap.main(Bootstrap.java:51) [org.wso2.micro.integrator.bootstrap-1.2.0.jar:1.2.0]
```
- It seems `[transport.jms]` repeated twice for the sender and the listener

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
1.2.0-rc1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Vathsan** [comment]
We have added `[transport.jms]` twice so that we can enable JMS listener and JMS sender individually. When enabling both we need to modify the configuration as follows,
```
[transport.jms]
sender_enable = true
listener_enable = true
```

**Comment by indikasampath2000** [comment]
Is that mentioned in the document?

**Comment by Vathsan** [comment]
> Is that mentioned in the document? If not, we have to explain that.

I could not find any reference regarding the above configuration in our documentation. We should add this in our docs. @nilminiwso2 let's update the docs with the relevant details.

**Comment by tishan89** [comment]
@nilminiwso2 We need to add a small note to docs here. This[1] is the content to be added. Lets get is done and close off this.
