### ISSUE TITLE
Cannot run file connector 4.0.0 with EI 6.1.0

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#2016]
**Description:**

When file connector 4.x.x is run with EI 6.0.0 or EI 6.1.0 following exception is thrown. 

```
[2020-11-17 08:58:24,586] [EI-Core] ERROR - NativeWorkerPool Uncaught exception
java.lang.NoSuchMethodError: org.apache.commons.vfs2.FileObject.isFolder()Z
	at org.wso2.carbon.connector.operations.ReadFile.connect(ReadFile.java:117)
	at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32)
	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:99)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:61)
	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:104)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:148)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:84)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:99)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:61)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:343)
	at org.apache.synapse.rest.API.process(API.java:418)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:123)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:101)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:69)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:304)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:78)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:326)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:372)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by abeykoon** [comment]
This should be due to the fact that EI 6.1.0 uses an old version of VFS library.

**Comment by GDLMadushanka** [comment]
deprecated product version
