### ISSUE TITLE
Exceptions thrown at server startup when keystores are configured

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/micro-integrator#2019]
**Description:**
Modify the wso2carbon.jks with passwords changed of the keystore. Add the following configuration to the deployment.toml
```
[keystore.primary]
password = "pwd"             # infered
alias = "wso2carbon"                # infered
key_password = "**pwd**"  
```

The server startup fails with multiple errors.
Issue 01
```
ERROR {org.apache.synapse.transport.nhttp.config.ServerConnFactoryBuilder} - EI_INTERNAL_HTTPS_INBOUND_ENDPOINT Error opening Key store : repository/resources/security/wso2carbon.jks java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:792)
        .....
        Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:790)
```

Need to add the following in the deployment.toml to over come the issue
```
[internal_api_ssl_config]
key_store.password = "pwd"
key_store.key_password = "pwd"
trust_store.password = "pwd"
```

Issue 02
```
[2020-11-16 16:07:33,147]  INFO {org.ops4j.pax.logging.spi.support.EventAdminConfigurationNotifier} - Logging configuration changed. (Event Admin service unavailable - no notification sent).
[2020-11-16 16:07:37,005] ERROR {org.wso2.micro.integrator.crypto.provider.internal.DefaultCryptoProviderComponent} - An error occurred while activating 'org.wso2.carbon.crypto.provider' component. org.wso2.carbon.crypto.api.CryptoException: An error occurred while loading the internal keystore using the configurations in 'Security.InternalKeyStore' block.
	at org.wso2.micro.integrator.crypto.provider.internal.DefaultCryptoProviderComponent.getKeyStoreBasedInternalCryptoProviderFromServerConfiguration(DefaultCryptoProviderComponent.java:202)
	at org.wso2.micro.integrator.crypto.provider.internal.DefaultCryptoProviderComponent.registerServiceImplementations(DefaultCryptoProviderComponent.java:98)
....
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
```
Need to modify the carbon.xml as follows to overcome this.
```
<InternalKeyStore>
            ....
            <Password>pwd</Password>
            <!-- Private Key alias-->
            <KeyAlias>wso2carbon</KeyAlias>
            <!-- Private Key password-->
            <KeyPassword>pwd</KeyPassword>
        </InternalKeyStore>
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
MI-1.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sdkottegoda** [comment]
Closing since this has been fixed
