### ISSUE TITLE
Publishing a Custom Swagger Document Not Working

### ISSUE THREAD

**Issue by tharakamd** [wso2/micro-integrator#2037]
**Description:**
When a custom Swagger definition is given to an API, the complete Swagger is not loading. It's giving a generated Swagger definition not the given custom Swagger file.

**Affected Product Version:**
MI 1.2.0

**Steps to reproduce:**
- Create new integrations project with a registry project in Integration Studio.
- Go to the REST API wizard.
-  Select the `Generate API using swagger definition` option
- Then select the attached swagger JSON file as the `Swagger Destination File` and add the registry path.
- Host the API and go to the swagger definition.
[swagger_updated.zip](https://github.com/wso2/micro-integrator/files/5768810/swagger_updated.zip)

**Comment by Vathsan** [comment]
With the fix, we can retrieve the swagger.json file without any issues. However, we try to get swagger.yaml, we could see the following exception,
```
[2021-01-08 17:15:50,729] ERROR {NativeWorkerPool} - Uncaught exception java.lang.NoClassDefFoundError: org/wso2/carbon/integrator/core/json/utils/GSONUtils
	at org.wso2.micro.integrator.transport.handlers.utils.SwaggerUtils.getAPISwagger(SwaggerUtils.java:339)
	at org.wso2.micro.integrator.transport.handlers.requestprocessors.swagger.format.SwaggerYamlProcessor.process(SwaggerYamlProcessor.java:51)
	at org.wso2.micro.integrator.transport.handlers.PassThroughNHttpGetProcessor.processWithGetProcessor(PassThroughNHttpGetProcessor.java:147)
	at org.wso2.micro.integrator.transport.handlers.PassThroughNHttpGetProcessor.process(PassThroughNHttpGetProcessor.java:317)
	at org.apache.synapse.transport.passthru.ServerWorker.processHttpRequestUri(ServerWorker.java:761)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:169)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.integrator.core.json.utils.GSONUtils cannot be found by synapse-nhttp-transport_2.1.7.wso2v182
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```
This error is happening because the imported GSONUtils class package is from `org.wso2.carbon.integrator.core.json.utils` 
which is wrong. It needs to be corrected as `org.wso2.micro.integrator.core.json.utils`.

**Comment by Vathsan** [comment]
The following fix https://github.com/wso2/micro-integrator/commit/1b45727b81d4a8822ed3f0fd65af567e04179281#diff-b15258acaa2b791edb2bd3d76856aabbb7b2114b3c58a7b23d6b07ba36c65bd4R371 address the issue in retrieving swagger.yaml definition in the master branch
