### ISSUE TITLE
ClassNotFoundException upon server startup in MI-1.2.0.4

### ISSUE THREAD

**Issue by Vathsan** [wso2/micro-integrator#2056]
**Description:**
When starting MI 1.2.04 the following error is thrown,
```
[2021-01-19 09:50:52,056] ERROR {SynapseHandlersLoader} - Error creating Handler for class name : org.wso2.micro.integrator.dataservices.odata.endpoint.ODataPassThroughHandler java.lang.ClassNotFoundException: org.wso2.micro.integrator.dataservices.odata.endpoint.ODataPassThroughHandler cannot be found by synapse-core_2.1.7.wso2v182_2
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.synapse.config.SynapseHandlersLoader.createHandler(SynapseHandlersLoader.java:102)
	at org.apache.synapse.config.SynapseHandlersLoader.loadHandlers(SynapseHandlersLoader.java:81)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.<init>(Axis2SynapseEnvironment.java:194)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.<init>(Axis2SynapseEnvironment.java:202)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.<init>(Axis2SynapseEnvironment.java:209)
	at org.apache.synapse.Axis2SynapseController.createSynapseEnvironment(Axis2SynapseController.java:388)
	at org.apache.synapse.ServerManager.start(ServerManager.java:187)
	at org.wso2.micro.integrator.initializer.ServiceBusInitializer.initESB(ServiceBusInitializer.java:336)
	at org.wso2.micro.integrator.initializer.ServiceBusInitializer.activate(ServiceBusInitializer.java:151)
```

**Suggested Labels:**
Bug

**Affected Product Version:**
MI-1.2.0.4

**Steps to reproduce:**
Start MI-1.2.0.4 server

**Comment by arunans23** [comment]
This is a U2 specific issue. Might occur in future releases. Hence we need to come up with a solution to overcome this.
