### ISSUE TITLE
Unable to read the Environment variable using $SYSTEM:variableName

### ISSUE THREAD

**Issue by raghavendra-centime** [wso2/micro-integrator#2098]
**Description:**

Unable to read the environment variable in the WSO2 micro-integrator.

I'm setting the environment variable and trying to use the $SYSTEM:VAR syntax to infer the vfs uri and it is not working.

Just to cross check, if the environment variable was set properly, I tried this simple code:

public class Test {

    public static void main(String[] args) {
        System.out.println(System.getenv("uploadDirectory"));
        
    }
}
and it was able to print the variable that was set. However, from the wso2 code, it's not able to infer it.

Also, to debug I've tried this script mediator:
 <script language="js">mc.setProperty("envVariables",java.lang.System.getenv().toString());</script>

It was also able to print the value of the environment varibale "uplaodDirectory" along with other environment variables.

References:
https://ei.docs.wso2.com/en/latest/micro-integrator/develop/injecting-parameters/

**Suggested Labels:**
bug

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
mac os catalina, WSO2 Micro Integrator v1.2.0,
Integration studio 7.1.0

**Steps to reproduce:**

1) set the environment varibale uploadDirectory to the required path
     a) In .zshrc "export uploadDirectory = vfs:file///some/path"
     b) activate the profile by running . ~/.zshrc
     c) verify that environment variable is set, echo $uploadDirectory - should print the path set.

In the code, refer the exported variable as in the below code.
`<call>
                          <endpoint>
                            <address uri="$SYSTEM:uploadDirectory">
                                <suspendOnFailure>
                                    <initialDuration>-1</initialDuration>
                                    <progressionFactor>1</progressionFactor>
                                </suspendOnFailure>
                                <markForSuspension>
                                    <retriesBeforeSuspension>0</retriesBeforeSuspension>
                                </markForSuspension>
                            </address>
                        </endpoint>
</call>`
  
**Expected** : the uri for address endpoint should be inferred.
**Actual**: [2021-02-16 12:57:38,187] ERROR {SynapseXPath} - Evaluation of the XPath expression $SYSTEM:uploadDirectory resulted in an error org.jaxen.UnresolvableException: Variable uploadDirectory
	at org.jaxen.SimpleVariableContext.getVariableValue(SimpleVariableContext.java:141)
	at org.apache.synapse.util.xpath.SynapseXPathVariableContext.getVariableValue(SynapseXPathVariableContext.java:264)
	at org.jaxen.ContextSupport.getVariableValue(ContextSupport.java:215)
	at org.jaxen.Context.getVariableValue(Context.java:196)
	at org.jaxen.expr.DefaultVariableReferenceExpr.evaluate(DefaultVariableReferenceExpr.java:106)
	at org.jaxen.expr.DefaultXPathExpr.asList(DefaultXPathExpr.java:102)
	at org.jaxen.BaseXPath.selectNodesForContext(BaseXPath.java:675)
	at org.jaxen.BaseXPath.selectNodes(BaseXPath.java:215)
	at org.jaxen.BaseXPath.evaluate(BaseXPath.java:175)
	at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:406)
	at org.apache.synapse.mediators.MediatorProperty.getEvaluatedExpression(MediatorProperty.java:139)
	at org.apache.synapse.mediators.builtin.LogMediator.setCustomProperties(LogMediator.java:236)
	at org.apache.synapse.mediators.builtin.LogMediator.getCustomLogMessage(LogMediator.java:153)
	at org.apache.synapse.mediators.builtin.LogMediator.getLogMessage(LogMediator.java:139)
	at org.apache.synapse.mediators.builtin.LogMediator.mediate(LogMediator.java:108)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.config.xml.AnonymousListMediator.mediate(AnonymousListMediator.java:37)
	at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:205)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:226)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:458)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Related Issues:**

**Comment by GDLMadushanka** [comment]
Tested and working in the latest version.
ps: need to change vfs:file///some/path to vfs:file:///some/path
