### ISSUE TITLE
Users should have capability to access raw payload when there's an exception

### ISSUE THREAD

**Issue by mettaramesh** [wso2/micro-integrator#2130]
**Description:**

Users should have capability to access input raw data payload to audit ( to Database or NoSQL DB) the incoming payload though its syntactically incorrect payload. 
 it's good to provide access to the raw bytes using this default context constant field : **RAW_PAYLOAD** to the user so that payload can be audited to Datasources  for correcting and later reprocessing.

**Suggested Labels:**
Apache synapse

**Suggested Assignees:**
N/A

**Affected Product Version:**
MI 7.1.1  ( ESB)

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
create a proxy service and send an xml payload with syntax error. In message building step, Control  directly hits fault sequence with below exception not giving chance to preserve the payload for later fault handling.

```
Caused by: com.ctc.wstx.exc.WstxParsingException: Unexpected close tag </foobar>; expected </foo>.
 at [row,col {unknown-source}]: [12,23]
	at com.ctc.wstx.sr.StreamScanner.constructWfcException(StreamScanner.java:606)
	at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:479)
	at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:464)
	at com.ctc.wstx.sr.BasicStreamReader.reportWrongEndElem(BasicStreamReader.java:3283)
	at com.ctc.wstx.sr.BasicStreamReader.readEndElem(BasicStreamReader.java:3228)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2829)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1072)
	at org.apache.axiom.util.stax.wrapper.XMLStreamReaderWrapper.next(XMLStreamReaderWrapper.java:225)
	at org.apache.axiom.util.stax.dialect.DisallowDoctypeDeclStreamReaderWrapper.next(DisallowDoctypeDeclStreamReaderWrapper.java:34)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214)
	... 17 more
```
Along with below fields : ERROR_CODE, ERROR_MESSAGE, ERROR_DETAIL, ERROR_EXCEPTION
populate the field : RAW_PAYLOAD to allow users to log,/audit/reprocess,/send back to client/forward the invalid payload to reporting systems

**Related Issues:**
N/A

**Comment by mettaramesh** [comment]
pls ignore
