### ISSUE TITLE
[Email Connector] An exception is thrown during shutting down the server

### ISSUE THREAD

**Issue by Vathsan** [wso2/micro-integrator#2179]
**Description:**
After invoking a particular operation using the file connector (sending email) and shutting down the server the following exception is thrown,

```
[2021-03-25 11:38:40,363] ERROR {initializer} - [SCR] Error while attempting to deactivate instance of component Component[
	name = org.wso2.micro.integrator.initializer.ServiceBusInitializer
	activate = activate
	deactivate = deactivate
	modified =
	configuration-policy = optional
	factory = null
	autoenable = true
	immediate = true
	implementation = org.wso2.micro.integrator.initializer.ServiceBusInitializer
	state = Unsatisfied
	properties =
	serviceFactory = false
	serviceInterface = null
	references = {
		Reference[name = config.context.service, interface = org.wso2.micro.integrator.core.services.Axis2ConfigurationContextService, policy = dynamic, cardinality = 1..1, target = null, bind = setConfigurationContextService, unbind = unsetConfigurationContextService]
		Reference[name = org.wso2.carbon.ndatasource, interface = org.wso2.micro.integrator.ndatasource.core.DataSourceService, policy = dynamic, cardinality = 1..1, target = null, bind = setDatasourceHandlerService, unbind = unsetDatasourceHandlerService]
		Reference[name = org.wso2.micro.integrator.core.services.CarbonServerConfigurationService, interface = org.wso2.micro.integrator.core.services.CarbonServerConfigurationService, policy = dynamic, cardinality = 1..1, target = null, bind = setServerConfigurationService, unbind = unsetServerConfigurationService]
		Reference[name = org.wso2.micro.integrator.ntask.core.service.TaskService, interface = org.wso2.micro.integrator.ntask.core.service.TaskService, policy = dynamic, cardinality = 1..1, target = null, bind = setTaskService, unbind = unsetTaskService]
		Reference[name = osgi.configadmin.service, interface = org.osgi.service.cm.ConfigurationAdmin, policy = dynamic, cardinality = 1..1, target = null, bind = setConfigAdminService, unbind = unsetConfigAdminService]
		Reference[name = secret.callback.handler.service, interface = org.wso2.carbon.securevault.SecretCallbackHandlerService, policy = dynamic, cardinality = 1..1, target = null, bind = setSecretCallbackHandlerService, unbind = unsetSecretCallbackHandlerService]
	}
	located in bundle = org.wso2.micro.integrator.initializer_1.2.0 [192]
] java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.deactivate(ServiceComponent.java:363)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.deactivate(ServiceComponentProp.java:161)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.dispose(ServiceComponentProp.java:387)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.dispose(ServiceComponentProp.java:102)
	at org.eclipse.equinox.internal.ds.InstanceProcess.disposeInstances(InstanceProcess.java:344)
	at org.eclipse.equinox.internal.ds.InstanceProcess.disposeInstances(InstanceProcess.java:306)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:368)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:227)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.unregisterServices(ServiceRegistry.java:668)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.close(BundleContextImpl.java:133)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1029)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:370)
	at org.eclipse.osgi.container.Module.doStop(Module.java:653)
	at org.eclipse.osgi.container.Module.stop(Module.java:515)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1861)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1753)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:202)
	at org.eclipse.osgi.container.Module.doStop(Module.java:653)
	at org.eclipse.osgi.container.Module.stop(Module.java:515)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:220)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AbstractMethodError: org.wso2.carbon.connector.connection.EmailConnection.close()V
	at org.wso2.carbon.connector.core.connection.ConnectionHandler.closeConnection(ConnectionHandler.java:189)
	at org.wso2.carbon.connector.core.connection.ConnectionHandler.shutdownConnections(ConnectionHandler.java:156)
	at org.wso2.carbon.connector.operations.EmailConfig.destroy(EmailConfig.java:57)
	at org.apache.synapse.mediators.ext.ClassMediator.destroy(ClassMediator.java:111)
	at org.apache.synapse.mediators.AbstractListMediator.destroy(AbstractListMediator.java:222)
	at org.apache.synapse.mediators.template.TemplateMediator.destroy(TemplateMediator.java:213)
	at org.apache.synapse.mediators.template.InvokeMediator.destroy(InvokeMediator.java:351)
	at org.apache.synapse.mediators.AbstractListMediator.destroy(AbstractListMediator.java:222)
	at org.apache.synapse.mediators.base.SequenceMediator.destroy(SequenceMediator.java:347)
	at org.apache.synapse.rest.Resource.destroy(Resource.java:468)
	at org.apache.synapse.rest.API.destroy(API.java:560)
	at org.apache.synapse.config.SynapseConfiguration.destroy(SynapseConfiguration.java:1532)
	at org.apache.synapse.Axis2SynapseController.destroySynapseConfiguration(Axis2SynapseController.java:542)
	at org.apache.synapse.ServerManager.stop(ServerManager.java:283)
	at org.wso2.micro.integrator.initializer.ServiceBusInitializer.deactivate(ServiceBusInitializer.java:252)
	... 34 more
```
**Suggested Labels:**
Bug, Connector

**Affected Product Version:**
Email connector 1.0.0

**Steps to reproduce:**
1. Use the following sample api (make sure to add the file connector),
```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/test" name="TestEmail" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="POST">
        <inSequence>
            <property expression="json-eval($.from)" name="from" scope="default" type="STRING"/>
            <property expression="json-eval($.to)" name="to" scope="default" type="STRING"/>
            <property expression="json-eval($.subject)" name="subject" scope="default" type="STRING"/>
            <property expression="json-eval($.content)" name="content" scope="default" type="STRING"/>
            <log level="full">
                <property name="Init" value="*********starting. initiating email connector***********"/>
                <property expression="$ctx:from" name="from"/>
                <property expression="$ctx:to" name="to"/>
                <property expression="$ctx:subject" name="subject"/>
                <property expression="$ctx:content" name="content"/>
            </log>
            <email.init>
                <host>smtp.gmail.com</host>
                <port>465</port>
                <name>smtpsconnection</name>
                <username>your@gmail.com</username>
                <password>yourpassword</password>
                <connectionType>SMTPS</connectionType>
            </email.init>
            <log level="full">
                <property name="Init" value="*********initiation done. sending email***********"/>
            </log>
            <email.send>
                <from>{$ctx:from}</from>
                <to>{$ctx:to}</to>
                <subject>{$ctx:subject}</subject>
                <content>{$ctx:content}</content>
                <contentType>text/plain</contentType>
            </email.send>
            <log level="full">
                <property name="Sending email" value="**********Completed**********"/>
            </log>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```
2. Invoke it using following payload,
```
{
    "from": "your@gmail.com",
    "to": "reciever@gmail.com",
    "subject": "Sample email - From Email connector",
    "content": "This is the body of the sample email"
}
```
3. Shut down the server

**Comment by abeykoon** [comment]
Tested with MI 4.0.0 Alpha pack with patch included for issue [1]. 
We are not supposed to use config with `init` operation. Even it is not visible in the connector operation panel. You need to use Connection view to define the connection [2]. 
When recommended approach is followed, issue does not happen. 

Hence closing the issue. 

[1]. https://github.com/wso2/micro-integrator/issues/1990
[2]. https://ei.docs.wso2.com/en/latest/micro-integrator/references/connectors/email-connector/email-connector-example/
