### ISSUE TITLE
Error when extracting the service port in Metric Handler

### ISSUE THREAD

**Issue by sachithKay** [wso2/micro-integrator#2296]
**Description:**
- In MI-1.2.0, when the observability handler is engaged with the configuration given below, it leads to a erroneous stack trace.
- This happens when 'services' is in the context of the API URL.
```
String index out of range: -13 java.lang.StringIndexOutOfBoundsException: String index out of range: -13
        at java.lang.String.substring(String.java:1967)
        at org.wso2.micro.integrator.observability.metric.handler.MetricHandler.getServiceInvokePort(MetricHandler.java:372)
        at org.wso2.micro.integrator.observability.metric.handler.MetricHandler.handleResponseOutFlow(MetricHandler.java:162)
        at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:192)
        at org.apache.synapse.mediators.builtin.RespondMediator.mediate(RespondMediator.java:46)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
        at org.apache.synapse.rest.Resource.process(Resource.java:331)
        at org.apache.synapse.rest.API.process(API.java:448)
        at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:134)
        at org.apache.synapse.rest.RESTRequestHandler.identifyAPI(RESTRequestHandler.java:154)
        at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:86)
        at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
        at 
```   

**Configuration**
```
[[synapse_handlers]]
name="CustomObservabilityHandler"
class="org.wso2.micro.integrator.observability.metric.handler.MetricHandler"
```

**Comment by sachithKay** [comment]
closing with https://github.com/wso2/micro-integrator/commit/7ac2a4780c412275aa42a18851f2cb10eef92167#diff-6798fcf51f7a49fe1764141b67c6160ded0837a97ce02da24916446e60362e94
