### ISSUE TITLE
Add ServerCrypto class to Micro Integrator

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#2320]
**Description:**
ServerCrypto is missing in micro integrator. Therefore the following error is thrown in MI 1.2.0

```
WARN {Loader} - org.wso2.micro.integrator.security.util.ServerCrypto java.lang.ClassNotFoundException: org.wso2.micro.integrator.security.util.ServerCrypto
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.osgi.internal.framework.ContextFinder.loadClass(ContextFinder.java:139)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.ws.security.util.Loader.loadClass(Loader.java:155)
	at org.apache.ws.security.components.crypto.CryptoFactory.loadClass(CryptoFactory.java:201)
	at org.apache.ws.security.components.crypto.CryptoFactory.getInstance(CryptoFactory.java:95)
	at org.apache.rampart.util.RampartUtil.getSignatureCrypto(RampartUtil.java:390)
	at org.apache.rampart.builder.BindingBuilder.getSignatureBuilder(BindingBuilder.java:359)
	at org.apache.rampart.builder.BindingBuilder.getSignatureBuilder(BindingBuilder.java:272)
	at org.apache.rampart.builder.AsymmetricBindingBuilder.doSignature(AsymmetricBindingBuilder.java:762)
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chanikag** [comment]
This is fixed with https://github.com/wso2/micro-integrator/pull/2180
