### ISSUE TITLE
Issue when running  securevault.sh in JDK 11

### ISSUE THREAD

**Issue by JanakaPushpakumara** [wso2/micro-integrator#2325]
**Description:**
When running securevault.sh in wso2mi-1.2.0 with JDK 11 following exception throws

```
janaka@janakap:~/WSo2/wso2mi-1.2.0$ sh bin/securevault.sh 
/home/janaka/wso2mi-1.2.0
:/home/janaka/wso2mi-1.2.0/wso2/components/plugins/org.wso2.micro.integrator.security_1.2.0.jar:
[Please Enter the Secret Alias]wso2carbon
[Please Enter Primary KeyStore Password of Carbon Server : ]

Primary KeyStore of Carbon Server is initialized Successfully

[Enter Plain Text Value : ]
[Please Enter Value Again : ]
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at org.wso2.micro.integrator.security.vault.VaultTool.doEncryption(VaultTool.java:212)
	at org.wso2.micro.integrator.security.vault.VaultTool.encryptedValue(VaultTool.java:153)
	at org.wso2.micro.integrator.security.vault.VaultTool.main(VaultTool.java:60)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 3 more

```

**Affected Product Version:**
wso2mi-1.2.0

**OS, DB, other environment details and versions:**    
jdk-11.0.11

**Related Issues:**
https://github.com/wso2/micro-integrator/issues/1591

**Comment by arunans23** [comment]
Securevault.sh is not needed in Micro Integrator. Should remove the file completely in future releases.
