### ISSUE TITLE
Cache mediator does not work in multi threaded environment

### ISSUE THREAD

**Issue by prashant-centime** [wso2/micro-integrator#2339]
**Description:**
We are using cache mediator in a sequence which is called from an inbound endpoint. The inbound endpoint is configured to be used in non-sequential way. The cache mediator init method throws **"o.w.c.m.c.CacheMediator : MBean implementation is not compliant with JMX specification standard MBean.
javax.management.InstanceAlreadyExistsException: org.wso2.carbon.mediator.cache:type=Cache,tenant=carbon.super"**

Following is the complete stack trace.

o.w.c.m.c.CacheMediator : MBean implementation is not compliant with JMX specification standard MBean.
javax.management.InstanceAlreadyExistsException: org.wso2.carbon.mediator.cache:type=Cache,tenant=carbon.super
at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
at org.wso2.carbon.mediator.cache.CacheMediator.exposeInvalidator(CacheMediator.java:612)
at org.wso2.carbon.mediator.cache.CacheMediator.init(CacheMediator.java:201)
at org.apache.synapse.mediators.AbstractListMediator.init(AbstractListMediator.java:200)
at org.apache.synapse.mediators.base.SequenceMediator.init(SequenceMediator.java:315)
at org.apache.synapse.core.axis2.Axis2MessageContext.getSequence(Axis2MessageContext.java:182)
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:201)
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
at org.apache.synapse.mediators.MediatorWorker.run(MediatorWorker.java:87)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

I think the issue is with the exposeInvalidator() method in the Cache mediator. I think it is not thread safe especially the following lines:

**Set<ObjectName> set = mserver.queryNames(cacheMBeanObjName, null);
            if (set.isEmpty()) {
}**

**Suggested Labels:**
Cache Mediator, multi-threading, non-sequential, inbound-endpoint, jmx

**Suggested Assignees:**

**Affected Product Version:**
mi 1.2.0
**OS, DB, other environment details and versions:**    
macOS, linux, mi 1.2.0 docker image and aws eks.
**Steps to reproduce:**
Configure the inbound endpoint to run in non-sequential way. Input multiple kafka messages and observe the cache mediator.

**Related Issues:**

**Comment by nandika** [comment]
Can you elaborate the scenario. If you can provide a sample configuration to reproduce this would be really useful.

**Comment by malakaganga** [comment]
There hasn't been a response so closing the issue please reopen the issue if it's required.
