### ISSUE TITLE
Unwanted payload transformation to SOAP that derives on a Error:  "org.apache.axis2.AxisFault: #getNewJsonPayload. Could not save JSON payload. Invalid input stream found. Payload is no a JSON String."

### ISSUE THREAD

**Issue by neogreco** [wso2/micro-integrator#2346]
**Description:**
Im creating a REST API on Integrator Studio.
I need to do several calls to Facebook Graph API and to my backend.
As i undertand, facebook works with json.
In particular im making a POST call from a POST resource of my REST API.
When i look at the payload before the facebook call, i found that the json data is missing and the body was transformed to soap message.
Ive tried to do the same to a mock service, and i found the json payload untoched. And it works well. 
The only difference between the calls, besides the endpoint server, is that the facebook one has a query parameter. 

**Suggested Assignees:**

**Affected Product Version:**
Integration Studio 8

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Create a new REST API with a post resource
- Add a inline endpoint call to a facebook graph api like "https://graph.facebook.com/v11.0/act_{ad_account_id}/campaigns"
- Test the api with the integrated micro integrator server.
- The call will not work and crash with an axis2 error:
```
org.apache.axis2.AxisFault: #getNewJsonPayload. Could not save JSON payload. Invalid input stream found. Payload is not a JSON string.
at org.apache.synapse.commons.json.JsonUtil.getNewJsonPayload(JsonUtil.java:872)
```

**Related Issues:**

**Comment by arunans23** [comment]
1) Can you attach a simplified version of your API sequence? 

2) Are you sending a valid JSON payload in your POST Rest call?

3) Are you sending the correct Content-Type Header `application/json` in your POST request?

**Comment by neogreco** [comment]
This is the first and working example:
```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/test" name="json" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="POST">
        <inSequence>
         <log>
                <property expression="json-eval($)" name="JSON-Payload"/>
            </log>
            <property name="messageType" scope="axis2" type="STRING" value="application/json"/>
            <property name="ContentType" scope="axis2" type="STRING" value="application/json"/>
            <property name="CHARACTER_SET_ENCODING" scope="axis2" type="STRING" value="UTF-8"/>
            <property name="DISABLE_CHUNKING" scope="axis2" type="STRING" value="true"/>
            <property name="QUOTE_STRING_IN_PAYLOAD_FACTORY_JSON" scope="default" type="STRING" value="true"/>
            <log level="full"/>
            <call>
                <endpoint>
                    <http method="post" statistics="enable" trace="enable" uri-template="https://reqres.in/api/register">
                        <suspendOnFailure>
                            <initialDuration>-1</initialDuration>
                            <progressionFactor>1</progressionFactor>
                        </suspendOnFailure>
                        <markForSuspension>
                            <retriesBeforeSuspension>0</retriesBeforeSuspension>
                        </markForSuspension>
                    </http>
                </endpoint>
                <source type="body"/>
                <target type="body"/>
            </call>
            <log category="DEBUG" level="full"/>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```
This json is on the request
```
{
    "email": "eve.holt@reqres.in",
    "password": "pistol"
  }
```

And here the facebook request, that fails
```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/fb" name="facebookPost" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="POST">
        <inSequence>
        
          <log>
                <property expression="json-eval($)" name="JSON-Payload"/>
            </log>
            <property name="messageType" scope="axis2" type="STRING" value="application/json"/>
            <property name="ContentType" scope="axis2" type="STRING" value="application/json"/>
            <property name="CHARACTER_SET_ENCODING" scope="axis2" type="STRING" value="UTF-8"/>
            <property name="DISABLE_CHUNKING" scope="axis2" type="STRING" value="true"/>
            <property name="QUOTE_STRING_IN_PAYLOAD_FACTORY_JSON" scope="default" type="STRING" value="true"/>
            <log level="full"/>
            <call>
                <endpoint>
                    <http method="post" statistics="enable" trace="enable" uri-template="https://graph.facebook.com/v11.0/act_{ad_account_id}/campaigns">
                        <suspendOnFailure>
                            <initialDuration>-1</initialDuration>
                            <progressionFactor>1</progressionFactor>
                        </suspendOnFailure>
                        <markForSuspension>
                            <retriesBeforeSuspension>0</retriesBeforeSuspension>
                        </markForSuspension>
                    </http>
                    <property expression="ad_account_id" name="ad_account_id"/>
                </endpoint>
                <source type="body"/>
                <target type="body"/>
            </call>
            <log level="full"/>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```


On the request iyou will need a facebook acoount:

**Comment by neogreco** [comment]
UPDATE: I've added an extra line for the facebook call.
`<header name="Accept" value="application/json" scope="transport"/>`
In this way it seems that the payload is not modified,
But still have the axis2 error:
```
This engine will expire all callbacks after GLOBAL_TIMEOUT: 120 seconds, irrespective of the timeout action, after the specified or optional timeout
[2021-07-14 17:04:05,959] ERROR {JsonStreamBuilder} - Error occurred while processing document for application/json java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.micro.integrator.core.json.JsonStreamBuilder.processDocument(JsonStreamBuilder.java:69)
	at org.apache.synapse.transport.passthru.util.DeferredMessageBuilder.getDocument(DeferredMessageBuilder.java:153)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:169)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:122)
	at org.apache.synapse.mediators.AbstractListMediator.buildMessage(AbstractListMediator.java:152)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:95)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:242)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.mediateFromContinuationStateStack(Axis2SynapseEnvironment.java:820)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:322)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:608)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:207)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:298)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault: #Can not parse stream. MessageID: urn:uuid:8b318f4f-3f17-4831-8f60-5426f7c25f15. Error>>> #getNewJsonPayload. Could not save JSON payload. Invalid input stream found. Payload is not a JSON string.
	at org.apache.synapse.commons.json.JsonUtil.getNewJsonPayload(JsonUtil.java:888)
	at org.apache.synapse.commons.json.JsonStreamBuilder.processDocument(JsonStreamBuilder.java:43)
	... 21 more
Caused by: org.apache.axis2.AxisFault: #getNewJsonPayload. Could not save JSON payload. Invalid input stream found. Payload is not a JSON string.
	at org.apache.synapse.commons.json.JsonUtil.getNewJsonPayload(JsonUtil.java:872)
	... 22 more

[2021-07-14 17:04:05,961] ERROR {DeferredMessageBuilder} - Error building message org.apache.axis2.AxisFault
	at org.wso2.micro.integrator.core.json.JsonStreamBuilder.processDocument(JsonStreamBuilder.java:73)
	at org.apache.synapse.transport.passthru.util.DeferredMessageBuilder.getDocument(DeferredMessageBuilder.java:153)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:169)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:122)
	at org.apache.synapse.mediators.AbstractListMediator.buildMessage(AbstractListMediator.java:152)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:95)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:242)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.mediateFromContinuationStateStack(Axis2SynapseEnvironment.java:820)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:322)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:608)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:207)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:298)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2021-07-14 17:04:05,961] ERROR {RelayUtils} - Error while building Passthrough stream org.apache.axis2.AxisFault
	at org.wso2.micro.integrator.core.json.JsonStreamBuilder.processDocument(JsonStreamBuilder.java:73)
	at org.apache.synapse.transport.passthru.util.DeferredMessageBuilder.getDocument(DeferredMessageBuilder.java:153)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:169)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:122)
	at org.apache.synapse.mediators.AbstractListMediator.buildMessage(AbstractListMediator.java:152)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:95)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:242)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.mediateFromContinuationStateStack(Axis2SynapseEnvironment.java:820)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:322)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:608)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:207)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:298)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2021-07-14 17:04:05,962] ERROR {SequenceMediator} - {api:facebookPost} Error while building message. Error while building Passthrough stream org.apache.axis2.AxisFault: Error while building Passthrough stream
	at org.apache.synapse.transport.passthru.util.RelayUtils.handleException(RelayUtils.java:453)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:216)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:122)
	at org.apache.synapse.mediators.AbstractListMediator.buildMessage(AbstractListMediator.java:152)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:95)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:242)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.mediateFromContinuationStateStack(Axis2SynapseEnvironment.java:820)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:322)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:608)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:207)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:298)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault
	at org.wso2.micro.integrator.core.json.JsonStreamBuilder.processDocument(JsonStreamBuilder.java:73)
	at org.apache.synapse.transport.passthru.util.DeferredMessageBuilder.getDocument(DeferredMessageBuilder.java:153)
	at org.apache.synapse.transport.passthru.util.RelayUtils.buildMessage(RelayUtils.java:169)
	... 14 more

[2021-07-14 17:07:05,608]  INFO {SourceHandler} - Writer null when calling informWriterError
```

**Comment by arunans23** [comment]
Two suggestions :
1. According to the axis2 stacktrace you have posted, it seems the response coming from Facebook is not in a JSON format. You can verify that by enabling [wirelogs](https://ei.docs.wso2.com/en/latest/micro-integrator/develop/using-wire-logs/). In your case you need to change settings inside the MI runtime inside the Integration Studio location. (Change OFF to DEBUG for `logger.synapse-transport-http-wire.level` in `<MI_HOME>/conf/log4j2.properties`)

2. The property you have defined inside call mediator `<property expression="ad_account_id" name="ad_account_id"/>`. I am not sure whether this is reading the account_id correctly given that you are using an expression here. From the above wire logs, please verify that whether the required facebook URL is called.

**Comment by neogreco** [comment]
Thank you Arunan! Finally it works!
- We need to be very carefully, the query params for an endpoint works only if are declared first and with the sufix "uri.var".
` <property expression="json-eval($.ad_account_id)" name="uri.var.ad_account_id"/>`
That for me was an anti-feature.  Not user friendly.
- I dont know why Facebook return sometimes, or most of the times, with an valid json error message, a set of invalid characters, that axis2 cant read. Will be nice that we can interpretate this chars somehow or filter them. Maybe its about the message content lenght with a wrong value.
I leave here also the final xml with some test logs included.
```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/fb" name="facebookPost" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="POST">
        <inSequence>
            <header name="Accept" scope="transport" value="application/json"/>
            <log>
                <property expression="json-eval($)" name="JSON-Payload"/>
            </log>
            <property name="messageType" scope="axis2" type="STRING" value="application/json"/>
            <property name="ContentType" scope="axis2" type="STRING" value="application/json"/>
            <property name="CHARACTER_SET_ENCODING" scope="axis2" type="STRING" value="UTF-8"/>
            <property name="DISABLE_CHUNKING" scope="axis2" type="STRING" value="true"/>
            <property name="QUOTE_STRING_IN_PAYLOAD_FACTORY_JSON" scope="default" type="STRING" value="true"/>
            <property expression="json-eval($.ad_account_id)" name="uri.var.ad_account_id"/>
            <log>
                <property expression="uri.var.ad_account_id" name="id1"/>
                <property expression="json-eval($.ad_account_id)" name="id2"/>
                <property expression="$body//ad_account_id" name="id3"/>
                <property expression="get-property(ad_account_id)" name="id4"/>
                <property expression="get-property(var.ad_account_id)" name="id5"/>
            </log>
            <log level="full"/>
            <call>
                <endpoint>
                    <http method="post" statistics="enable" trace="enable" uri-template="https://graph.facebook.com/v11.0/act_{uri.var.ad_account_id}/campaigns">
                        <suspendOnFailure>
                            <initialDuration>-1</initialDuration>
                            <progressionFactor>1</progressionFactor>
                        </suspendOnFailure>
                        <markForSuspension>
                            <retriesBeforeSuspension>0</retriesBeforeSuspension>
                        </markForSuspension>
                    </http>
                </endpoint>
                <source type="body"/>
                <target type="body"/>
            </call>
            <log level="full"/>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>

```
