### ISSUE TITLE
data service not works

### ISSUE THREAD

**Issue by AnasAltarazi1998** [wso2/micro-integrator#2519]
when I tried to build a rest api for a data source (mysql database) I faced this error by any request I sent.
`
Uncaught exception java.lang.AbstractMethodError: Method com/mysql/jdbc/PreparedStatement.isClosed()Z is abstract
	at com.mysql.jdbc.PreparedStatement.isClosed(PreparedStatement.java)
	at org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer.closeInvoked(StatementFinalizer.java:63)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:68)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:152)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:40)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:69)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
	at com.sun.proxy.$Proxy43.close(Unknown Source)
	at org.wso2.micro.integrator.dataservices.core.description.query.SQLDataServicesConnection.close(SQLDataServicesConnection.java:64)
	at org.wso2.micro.integrator.dataservices.core.TLConnectionStore.closeAll(TLConnectionStore.java:128)
	at org.wso2.micro.integrator.dataservices.core.dispatch.BatchDataServiceRequest.finalizeTx(BatchDataServiceRequest.java:135)
	at org.wso2.micro.integrator.dataservices.core.dispatch.BatchDataServiceRequest.processRequest(BatchDataServiceRequest.java:117)
	at org.wso2.micro.integrator.dataservices.core.dispatch.DataServiceRequest.dispatch(DataServiceRequest.java:358)
	at org.wso2.micro.integrator.dataservices.core.DataServiceProcessor.dispatch(DataServiceProcessor.java:40)
	at org.wso2.micro.integrator.dataservices.core.DBInOutMessageReceiver.invokeBusinessLogic(DBInOutMessageReceiver.java:81)
	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:42)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:375)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:434)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:182)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

what should I do to fix this error and have a response ?

**Comment by Vathsan** [comment]
Hi @AnasAltarazi1998, could you share your data service and api configs? I was able to call the data service without any issues. 
You may also use [Data Service Call Mediator](https://apim.docs.wso2.com/en/latest/reference/mediators/dss-mediator/) to invoke your data service.
