### ISSUE TITLE
NPE during server startup when connected to MI dashboard and JDBC user store

### ISSUE THREAD

**Issue by arunans23** [wso2/micro-integrator#2636]
**Description:**

While using dashboard with MI and mysql user store, during MI server startup the following error is thrown. Unable to login. 

```
[2022-03-10 12:51:40,733]  INFO {EventAdminConfigurationNotifier} - Logging configuration changed. (Event Admin service unavailable - no notification sent).
[2022-03-10 12:51:43,529]  INFO {AppDeployerServiceComponent} - Dashboard is configured. Initiating heartbeat component.
[2022-03-10 12:51:43,569]  INFO {PassThroughListeningIOReactorManager} - Pass-through HTTP Listener started on 0.0.0.0:8290
[2022-03-10 12:51:43,571]  INFO {PassThroughListeningIOReactorManager} - Pass-through HTTPS Listener started on 0.0.0.0:8253
[2022-03-10 12:51:43,572]  INFO {StartupFinalizer} - WSO2 Micro Integrator started in 5.40 seconds
[2022-03-10 12:51:43,662]  INFO {SecurityHandlerAdapter} - File based user store has been disabled. Carbon user store settings will be used.
[2022-03-10 12:51:43,676]  INFO {PassThroughListeningIOReactorManager} - Pass-through EI_INTERNAL_HTTP_INBOUND_ENDPOINT Listener started on 0.0.0.0:9201
[2022-03-10 12:51:43,685]  INFO {PassThroughListeningIOReactorManager} - Pass-through EI_INTERNAL_HTTPS_INBOUND_ENDPOINT Listener started on 0.0.0.0:9164
[2022-03-10 12:51:46,306]  INFO {ServiceComponent} - Initializing Security parameters
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
[2022-03-10 12:51:46,624]  INFO {AuthenticationHandlerAdapter} - User admin logged in successfully
[2022-03-10 12:51:47,166] ERROR {InboundHttpServerWorker} - Exception occurred when running org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpServerWorker java.lang.NullPointerException
	at org.wso2.micro.integrator.ndatasource.core.utils.DataSourceUtils.elementToStringWithMaskedPasswords(DataSourceUtils.java:168)
	at org.wso2.micro.integrator.management.apis.DataSourceResource.getDatasourceInformation(DataSourceResource.java:157)
	at org.wso2.micro.integrator.management.apis.DataSourceResource.invoke(DataSourceResource.java:92)
	at org.wso2.micro.integrator.management.apis.ApiResourceAdapter.invoke(ApiResourceAdapter.java:55)
	at org.wso2.carbon.inbound.endpoint.internal.http.api.InternalAPIDispatcher.dispatch(InternalAPIDispatcher.java:87)
	at org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpServerWorker.run(InboundHttpServerWorker.java:114)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by arunans23** [comment]
This is Error occurs when giving the user store DB password as empty.
