### ISSUE TITLE
NPE is thrown when DataServiceCall Mediator is used with SalesForce Inbound EP.

### ISSUE THREAD

**Issue by arunans23** [wso2/micro-integrator#2690]
**Description:**

StackTrace:

```
[2022-03-28 18:36:46,291] ERROR {SequenceMediator} - Runtime error occurred while mediating the message java.lang.NullPointerException
 at org.wso2.micro.integrator.mediator.dataservice.DataServiceCallMediator.handleSourceTypeBody(DataServiceCallMediator.java:155)
 at org.wso2.micro.integrator.mediator.dataservice.DataServiceCallMediator.mediate(DataServiceCallMediator.java:108)
 at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
 at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
 at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
 at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectInbound(Axis2SynapseEnvironment.java:486)
 at org.wso2.carbon.inbound.endpoint.protocol.generic.GenericPollingConsumer.injectMessage(GenericPollingConsumer.java:118)
 at org.wso2.carbon.inbound.endpoint.protocol.generic.GenericPollingConsumer.injectMessage(GenericPollingConsumer.java:73)
 at org.wso2.carbon.inbound.salesforce.poll.SalesforceStreamData.injectSalesforceMessage(SalesforceStreamData.java:313)
 at org.wso2.carbon.inbound.salesforce.poll.SalesforceStreamData.lambda$makeConnect$0(SalesforceStreamData.java:166)
 at org.wso2.carbon.inbound.salesforce.poll.EmpConnector$SubscriptionImpl.lambda$subscribe$0(EmpConnector.java:91)
 at org.cometd.common.AbstractClientSession$AbstractSessionChannel.notifyOnMessage(AbstractClientSession.java:597)
 at org.cometd.common.AbstractClientSession$AbstractSessionChannel.notifyMessageListeners(AbstractClientSession.java:588)
 at org.cometd.common.AbstractClientSession.notifyListeners(AbstractClientSession.java:294)
 at org.cometd.common.AbstractClientSession.receive(AbstractClientSession.java:260)
 at org.cometd.client.BayeuxClient.processMessage(BayeuxClient.java:822)
 at org.cometd.client.BayeuxClient.processMessages(BayeuxClient.java:618)
 at org.cometd.client.BayeuxClient.access$3100(BayeuxClient.java:100)
 at org.cometd.client.BayeuxClient$MessageTransportListener.onMessages(BayeuxClient.java:1190)
 at org.cometd.client.transport.LongPollingTransport$2.onComplete(LongPollingTransport.java:236)
 at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
 at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
 at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:454)
 at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:401)
 at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:266)
 at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1404)
 at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1246)
 at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:156)
 at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:117)
 at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)
 at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
 at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:174)
 at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
 at java.lang.Thread.run(Thread.java:748
```

Steps to reproduce:

1. Create a [SalesforceInboundEP](https://apim.docs.wso2.com/en/latest/reference/connectors/salesforce-connectors/sf-inbound-endpoint-example/)
2. Inside the Sequence, use a DSS Call Mediator with Source Type as Body.
```
<?xml version="1.0" encoding="UTF-8"?>
<sequence name="simple" xmlns="http://ws.apache.org/ns/synapse">	    <header name="action" scope="transport" value="urn:addEmployee"/>
            <payloadFactory media-type="xml">
                <format>
                    <addEmployee xmlns="http://ws.apache.org/ns/synapse">
                           <ID>123</ID>
                           <name>abc</>
                    </addEmployee>
                </format>
                <args>   
                </args>
            </payloadFactory>
         <dataServiceCall serviceName="DSSCallMediatorTest">
                <source type="body"/>
                <target type="body"/>
            </dataServiceCall>
	<drop/>
</sequence>
```
3. Deploy a Sample DataService.
```
<data disableLegacyBoxcarringMode="true" enableBatchRequests="true" enableBoxcarring="true" name="DSSCallMediatorTest" transports="http https local">
   <config enableOData="false" id="01">
      <property name="driverClassName">com.mysql.jdbc.Driver</property>
      <property name="url">jdbc:mysql://localhost:3306/employees</property>
      <property name="username">root</property>
      <property name="password"></property>
   </config>
   <query id="addEmployeeQuery" useConfig="01">
      <sql>insert into Test (ID, name) values(:ID,:name)</sql>
      <param name="ID" sqlType="STRING"/>
      <param name="name" sqlType="STRING"/>
   </query>
   <operation name="addEmployee" returnRequestStatus="true">
      <call-query href="addEmployeeQuery">
        <with-param name="ID" query-param="ID" />
      <with-param name="name" query-param="name" />
      </call-query>
   </operation>
</data>
```
4. When the InboundEP is invoked, the above stacktrace will be printed.

**Comment by arunans23** [comment]
This error will occur with any type of Inbound EP. Not specific to SalesforceInboundEP.
