### ISSUE TITLE
Exception in thread "pool-5-thread-1" java.lang.NullPointerException

### ISSUE THREAD

**Issue by al-mahd** [wso2/micro-integrator#2691]
Exception in thread "pool-5-thread-1" java.lang.NullPointerException
	at org.wso2.ei.dashboard.micro.integrator.MiArtifactsManager.processArtifacts(MiArtifactsManager.java:148)
	at org.wso2.ei.dashboard.micro.integrator.MiArtifactsManager.fetchAllArtifactsAndStore(MiArtifactsManager.java:135)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by dulanjalidilmi** [comment]
Hi @al-mahd ,

In order to investigate the issue more, please provide us with following information. 

1. MI and MI Dashboard version
2. Exact use-case with environment details

You can refer https://apim.docs.wso2.com/en/latest/observe/mi-observe/working-with-monitoring-dashboard/#! to set up MI and MI dashboard.

Best regards
Dilmi

**Comment by malakaganga** [comment]
Requested information hasn't been provided hence closing the issue. Please reopen if it's required.
