### ISSUE TITLE
ununderstandable error while runing integration studio project

### ISSUE THREAD

**Issue by mkassir95** [wso2/micro-integrator#2722]
Hello,
I am getting such error when running integration studio project
`Exception in thread "pool-15-thread-1" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 22 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at org.wso2.micro.integrator.initializer.utils.ServiceCatalogUtils.getAllServices(ServiceCatalogUtils.java:271)
	at org.wso2.micro.integrator.initializer.serviceCatalog.ServiceCatalogDeployer.run(ServiceCatalogDeployer.java:61)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 22 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 6 more`

How can I debug it?

**Comment by dulanjalidilmi** [comment]
Hi @mkassir95,

In order to investigate the issue more, please provide us with following information.

1. Integration Studio Version
2. The use case and steps to reproduce
3. Full stack-trace 

Best Regards
Dilmi

**Comment by malakaganga** [comment]
There hasn't been a response so closing the issue please reopen the issue if it's required.
