### ISSUE TITLE
MI throws an NPE when Kafka inbound endpoint is used with tracing enabled

### ISSUE THREAD

**Issue by wx-yz** [wso2/micro-integrator#2945]
Tracing config,

```
[mediation]
flow.statistics.capture_all= true
stat.tracer.collect_payloads= true
stat.tracer.collect_mediation_properties= true

[opentelemetry]
enable = true
logs = true
type = "jaeger"
host = "localhost"
port = 14250
```

Kafka inbound endpoint config
```
<?xml version="1.0" encoding="UTF-8"?>
<inboundEndpoint class="org.wso2.carbon.inbound.kafka.KafkaMessageConsumer" name="HyattKafkaRead" onError="kafkaErrSeq" sequence="kafkaReadSeq" suspend="false" xmlns="http://ws.apache.org/ns/synapse">
    <parameters>
        <parameter name="interval">1000</parameter>
        <parameter name="class">org.wso2.carbon.inbound.kafka.KafkaMessageConsumer</parameter>
        <parameter name="sequential">true</parameter>
        <parameter name="coordination">true</parameter>
        <parameter name="inbound.behavior">polling</parameter>
        <parameter name="sasl.jaas.config">$SYSTEM:KAFKA_AUTH</parameter>
        <parameter name="kafka.saslJaasConfig">$SYSTEM:KAFKA_AUTH</parameter>
        <parameter name="bootstrap.servers">pkc-6ojv2.us-west4.gcp.confluent.cloud:9092</parameter>
        <parameter name="security.protocol">SASL_SSL</parameter>
        <parameter name="sasl.mechanism">PLAIN</parameter>
        <parameter name="key.deserializer">org.apache.kafka.common.serialization.StringDeserializer</parameter>
        <parameter name="contentType">application/json</parameter>
        <parameter name="topic.name">reservations</parameter>
        <parameter name="group.id">hello</parameter>
        <parameter name="poll.timeout">100</parameter>
        <parameter name="value.deserializer">org.apache.kafka.common.serialization.StringDeserializer</parameter>
        <parameter name="kafka.schemaRegistryUrl">https://psrc-30dr2.us-central1.gcp.confluent.cloud</parameter>
        <parameter name="kafka.basicAuthCredentialsSource">USER_INFO</parameter>
        <parameter name="kafka.basicAuthUserInfo">{{ SR_API_KEY }}:{{ SR_API_SECRET }}</parameter>
    </parameters>
</inboundEndpoint>
```

NPE thrown,

```
[2023-08-22 14:52:05,987] ERROR {KafkaMessageConsumer} - Error while processing the Kafka inbound endpoint Message and the message should be in the format of application/json java.lang.NullPointerException
	at io.opentelemetry.context.Context.with(Context.java:169)
	at org.apache.synapse.aspects.flow.statistics.tracing.opentelemetry.management.handling.span.SpanHandler.startSpan(SpanHandler.java:215)
	at org.apache.synapse.aspects.flow.statistics.tracing.opentelemetry.management.handling.span.SpanHandler.startSpanOrBufferSequenceContinuationState(SpanHandler.java:167)
	at org.apache.synapse.aspects.flow.statistics.tracing.opentelemetry.management.handling.span.SpanHandler.handleOpenEntryEvent(SpanHandler.java:131)
	at org.apache.synapse.aspects.flow.statistics.collectors.OpenEventCollector.reportEntryEvent(OpenEventCollector.java:112)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectInbound(Axis2SynapseEnvironment.java:480)
	at org.wso2.carbon.inbound.kafka.KafkaMessageConsumer.injectMessage(KafkaMessageConsumer.java:265)
	at org.wso2.carbon.inbound.kafka.KafkaMessageConsumer.injectMessage(KafkaMessageConsumer.java:222)
	at org.wso2.carbon.inbound.kafka.KafkaMessageConsumer.commitRecords(KafkaMessageConsumer.java:137)
	at org.wso2.carbon.inbound.kafka.KafkaMessageConsumer.consumeKafkaRecords(KafkaMessageConsumer.java:100)
	at org.wso2.carbon.inbound.kafka.KafkaMessageConsumer.poll(KafkaMessageConsumer.java:369)
	at org.wso2.carbon.inbound.endpoint.protocol.generic.GenericTask.taskExecute(GenericTask.java:40)
	at org.wso2.carbon.inbound.endpoint.common.InboundTask.execute(InboundTask.java:43)
	at org.wso2.micro.integrator.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:105)
	at org.wso2.micro.integrator.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:63)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by sajinieKavindya** [comment]
Duplicate issue https://github.com/wso2/micro-integrator/issues/2971
Fixed with https://github.com/wso2/wso2-synapse/pull/2100
