### ISSUE TITLE
Cannot consume messages from a queue of RabbitMQ

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#3032]
In MI 4.2.0 when using rabbitMQ inbound endpoint, receiving a NullPointerException as below when consuming the messages.

ERROR {ForgivingExceptionHandler} - Consumer org.wso2.carbon.inbound.endpoint.protocol.rabbitmq.RabbitMQConsumer@11591e1c (amq.ctag-h_hV6K766PcIcOjhtNYq7Q) method handleDelivery for channel AMQChannel(amqp://guest@127.0.0.1:5672/,1) threw an exception for channel AMQChannel(amqp://guest@127.0.0.1:5672/,1) java.lang.NullPointerException
at org.apache.axis2.transport.rabbitmq.RabbitMQUtils.processReplyToHeader(RabbitMQUtils.java:489)
at org.apache.axis2.transport.rabbitmq.RabbitMQUtils.buildMessage(RabbitMQUtils.java:438)
at org.apache.axis2.transport.rabbitmq.RabbitMQUtils.buildMessage(RabbitMQUtils.java:539)
at org.wso2.carbon.inbound.endpoint.protocol.rabbitmq.RabbitMQInjectHandler.onMessage(RabbitMQInjectHandler.java:80)
at org.wso2.carbon.inbound.endpoint.protocol.rabbitmq.RabbitMQConsumer.handleDelivery(RabbitMQConsumer.java:213)
at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)

Steps to reproduce:

Publish the message using:

```
curl -X POST -i -u guest:guest 'http://localhost:15672/api/exchanges/%2f/excahnge_name/publish'
--data '{
"service": {
"api_version": "api_v1",
"endpointName": "consignments",
"serviceName": "logistics",
"operation": "create",
"methodName": null
},
"properties": {
"content_type": "application/json",
"correlation_id": "12345ab",
"reply_to": "rpc_queue"
},
"routing_key": "abc_queue",
"payload": "{\n"Test": "mytest11"\n}",
"payload_encoding": "string"
}'
```

**Comment by chanikag** [comment]
Fixed with https://github.com/wso2/wso2-axis2-transports/commit/8a726866dea5237b4977477430fa21cded6f8569
