### ISSUE TITLE
Issue with the Enrich Mediator

### ISSUE THREAD

**Issue by ayeshrodz** [wso2/micro-integrator#3070]
### Issue
The enrich mediator does not properly serialise the enriched content before getting cloned. The issue occurred with low server performance and can be observed when high stress levels (high TPS) received to MI.

### Reproducing steps

1. Download the MI pack.

2. Create a sample API including the enrich mediator to enrich an xml content.
```
e.g.
<enrich>
    <source clone="true" type="inline">
        <messageId>{$ctx:message}</messageId>
    </source>
    <target action="child" xmlns:xs="http://ws.apache.org/ns/synapse1" xpath="//xs:element/xs:subele"/>
</enrich>
```

3. Load test the API using a tool such as Postman.
e.g.
<img width="490" alt="image" src="https://github.com/wso2/micro-integrator/assets/6896061/1e1c8ab4-9f2f-4304-8ba6-8628fd8e0843">

4. Similar errors to the following, can be observed in carbon logs when the request tps gets increased.

```
[2023-12-27 16:31:48,728]  WARN {StAXOMBuilder} - Attempt to access a parser that has thrown a parse exception before; rethrowing the original exception.
[2023-12-27 16:31:48,729] ERROR {SequenceMediator} - {api:TestAPI} com.ctc.wstx.exc.WstxEOFException: Unexpected EOF; was expecting a close tag for element <messageId>
 at [row,col {unknown-source}]: [1,109] org.apache.axiom.om.OMException: com.ctc.wstx.exc.WstxEOFException: Unexpected EOF; was expecting a close tag for element <messageId>
 at [row,col {unknown-source}]: [1,109]
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:296)
	at org.apache.axiom.om.impl.llom.OMElementImpl.buildNext(OMElementImpl.java:653)
	at org.apache.axiom.om.impl.llom.OMNodeImpl.getNextOMSibling(OMNodeImpl.java:122)
	at org.apache.axiom.om.impl.traverse.OMChildrenIterator.getNextNode(OMChildrenIterator.java:36)
	at org.apache.axiom.om.impl.traverse.OMAbstractIterator.hasNext(OMAbstractIterator.java:58)
	at org.apache.axiom.om.impl.util.OMSerializerUtil.serializeChildren(OMSerializerUtil.java:554)
	at org.apache.axiom.om.impl.llom.OMElementImpl.internalSerialize(OMElementImpl.java:879)
	at org.apache.axiom.om.impl.llom.OMSerializableImpl.serialize(OMSerializableImpl.java:125)
	at org.apache.axiom.om.impl.llom.OMSerializableImpl.serialize(OMSerializableImpl.java:113)
	at org.apache.axiom.om.impl.llom.OMElementImpl.toString(OMElementImpl.java:992)
	at org.apache.synapse.mediators.elementary.EnrichMediator.mediate(EnrichMediator.java:193)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.api.Resource.process(Resource.java:342)
	at org.apache.synapse.api.API.process(API.java:463)
	at org.apache.synapse.api.AbstractApiHandler.apiProcess(AbstractApiHandler.java:95)
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:73)
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:84)
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:70)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:395)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:209)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.ctc.wstx.exc.WstxEOFException: Unexpected EOF; was expecting a close tag for element <messageId>
 at [row,col {unknown-source}]: [1,109]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedEOF(StreamScanner.java:677)
	at com.ctc.wstx.sr.BasicStreamReader.throwUnexpectedEOF(BasicStreamReader.java:5532)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2720)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1072)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.parserNext(StAXOMBuilder.java:681)
	at org.apache.axiom.om.impl.builder.StAXOMBuilder.next(StAXOMBuilder.java:214)
	at org.apache.axiom.om.impl.llom.OMSerializableImpl.build(OMSerializableImpl.java:78)
	at org.apache.axiom.om.impl.llom.OMElementImpl.build(OMElementImpl.java:722)
	at org.apache.axiom.om.impl.llom.OMElementImpl.cloneOMElement(OMElementImpl.java:1038)
	at org.apache.synapse.mediators.elementary.Source.evaluate(Source.java:208)
	at org.apache.synapse.mediators.elementary.EnrichMediator.mediate(EnrichMediator.java:255)
	... 19 more
```

Product : wso2mi-4.0.0
Update level : 104

**Comment by SanojPunchihewa** [comment]
Related issue for MI 420 : https://github.com/wso2/micro-integrator/issues/3296
