### ISSUE TITLE
log4j2 asynchronous support for WSO2 1.2.0

### ISSUE THREAD

**Issue by dilshanfa** [wso2/micro-integrator#3206]
### Problem

As we can see in the WSO2 APIM side we have provided a way to enable asynchronous feature. But seems like if you configure the same things in the MI we are facing a ClassNotFound issue

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/lmax/disruptor/EventTranslatorVararg
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.logging.log4j.core.async.AsyncLoggerContextSelector.createContext(AsyncLoggerContextSelector.java:46)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:145)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:70)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:57)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:148)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:121)
	at org.apache.logging.log4j.jcl.LogAdapter.getContext(LogAdapter.java:39)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
	at org.apache.logging.log4j.jcl.LogFactoryImpl.getInstance(LogFactoryImpl.java:40)
	at org.apache.logging.log4j.jcl.LogFactoryImpl.getInstance(LogFactoryImpl.java:55)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
	at org.wso2.micro.integrator.server.Main.<clinit>(Main.java:67)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.wso2.micro.integrator.bootstrap.Bootstrap.loadClass(Bootstrap.java:67)
	at org.wso2.micro.integrator.bootstrap.Bootstrap.main(Bootstrap.java:51)
Caused by: java.lang.ClassNotFoundException: com.lmax.disruptor.EventTranslatorVararg
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
```

### Steps to reproduce.

- Add the following line into '<MI_HOME>/conf/etc/pax-logging.properties' file. `org.ops4j.pax.logging.log4j2.async=true`
- Add the following parameter into '<MI_HOME>/bin/micro-integrator.sh' file, or pass it as a JVM parameter while starting the server. This system property will make all loggers async. 
`-Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector`

If you invoke a API with an inbuilt login mediator you can see the above error.

### Solution

As we can see [1] we need the disruptor-3.3.4.jar or higher but our mi pack contain disruptor-3.2.2.jar, So in order to get the support we need to get this feature we need to get this latest version.

I have download the 3.3.4 jar and replaced with the 3.2.2,jar and after that it will not show this error.

[1] https://logging.apache.org/log4j/2.x/manual/async.html#mixing-synchronous-and-asynchronous-loggers

### Affected Component

MI

### Version

1.2.0

**Comment by randomvariable** [comment]
Is this still valid? pom.xml shows 3.4.2
