### ISSUE TITLE
How to enable SNMP Monitoring on WSO2-MI 4.1.0

### ISSUE THREAD

**Issue by AlisonAbrantes** [wso2/micro-integrator#3226]
### Description

We have a Linux server (CentoS 8) in a private subnet, and we alredy have a wso2-mi running on this server. For porpuse of monitoring, we're trying do enable SNMP protocol on wso2-mi, we follow the instructions of official documentation, but something is not right, and we don't know what to do.

The Error: 
[2022-10-11 16:12:08,499] FATAL {ServiceBusInitializer} - Failed to initialize ESB due to a fatal error java.lang.NoClassDefFoundError: org/apache/log4j/Priority
        at org.snmp4j.log.Log4jLogFactory.createLogger(Log4jLogFactory.java:47)
        at org.snmp4j.log.LogFactory.getLogger(LogFactory.java:56)
        at org.snmp4j.agent.CommandProcessor.<clinit>(CommandProcessor.java:48)
        at org.apache.synapse.commons.snmp.SNMPAgent.<init>(SNMPAgent.java:77)
        at org.apache.synapse.commons.snmp.SynapseSNMPAgent.<init>(SynapseSNMPAgent.java:42)
        at org.wso2.micro.integrator.initializer.CarbonSynapseController.start(CarbonSynapseController.java:114)
        at org.apache.synapse.ServerManager.start(ServerManager.java:190)
        at org.wso2.micro.integrator.initializer.ServiceBusInitializer.initESB(ServiceBusInitializer.java:336)
        at org.wso2.micro.integrator.initializer.ServiceBusInitializer.activate(ServiceBusInitializer.java:151)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
        at org.wso2.micro.integrator.ntask.core.internal.TasksDSComponent.activate(TasksDSComponent.java:147)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
        at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
        at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
        at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
        at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Priority cannot be found by snmp4j_2.1.0_1.0.0
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)

How it happens?:
- Download the SNMP4j-2.1.0.jar and SNMP4j-Agent-2.0.6.jar files, copy then to MI_HOME/lib, and enable the propriety on deployment.toml file (MI_HOME/conf), using: 
  [synapse_properties]
  'synapse.snmp.enabled'=true
- start the micro-integrator.sh

Can anyone help us with this situation?

### Affected Component

MI

### Version

4.1.0

### Environment Details (with versions)

- Linux (Centos 8)
- WSO2 Micro-integrator 4.1.0
- JDK: openjdk version "1.8.0_242"
- Server in a private Subnet

### Suggested Labels

micro-integrator

**Comment by anupama-pathirage** [comment]
If you're still facing this issue, please feel free to raise your question in the `help-micro-integrator` channel on the [WSO2 Discord server](https://discord.com/invite/Xa5VubmThw)
