### ISSUE TITLE
Synapse Resource Generator fails when project contains mongoDB connector

### ISSUE THREAD

**Issue by ThusharaSampath** [wso2/micro-integrator#3271]
This happens when we generate swagger using synapse-resource-generator.jar in choreo component build. 

we are using resource generator version 1.0.24

Command Used : `java -jar synapse-resource-gen.jar oas output-directory=<directory>`

Error:

```bash
org.apache.synapse.SynapseException: Unknown mediator referenced by configuration element : {http://ws.apache.org/ns/synapse}mongodb
[builder] Error while resolving API. Generating default swagger
[builder] 	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:220)
[builder] 	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:46)
[builder] 	at org.apache.synapse.config.xml.SequenceMediatorFactory.createAnonymousSequence(SequenceMediatorFactory.java:70)
[builder] 	at org.apache.synapse.config.xml.rest.ResourceFactory.configureSequences(ResourceFactory.java:107)
[builder] 	at org.apache.synapse.config.xml.rest.ResourceFactory.createResource(ResourceFactory.java:50)
[builder] 	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:94)
[builder] 	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:54)
[builder] 	at com.wso2.choreo.synapse.executor.impl.OasGenerationExecutor.generateOasFile(OasGenerationExecutor.java:205)
[builder] 	at com.wso2.choreo.synapse.executor.impl.OasGenerationExecutor.execute(OasGenerationExecutor.java:138)
[builder] 	at com.wso2.choreo.synapse.SynapseResourceGenerator.main(SynapseResourceGenerator.java:30)
[builder] 
[builder] org.apache.synapse.SynapseException: Unknown mediator referenced by configuration element : {http://ws.apache.org/ns/synapse}mongodb
[builder] default-swagger.yaml generated successfullyError while resolving API. Generating default swagger
[builder] 	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:220)
[builder] 	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:46)
[builder] 	at org.apache.synapse.config.xml.SequenceMediatorFactory.createAnonymousSequence(SequenceMediatorFactory.java:70)
[builder] 	at org.apache.synapse.config.xml.rest.ResourceFactory.configureSequences(ResourceFactory.java:107)
[builder] 	at org.apache.synapse.config.xml.rest.ResourceFactory.createResource(ResourceFactory.java:50)
[builder] 	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:94)
[builder] 	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:54)
[builder] 	at com.wso2.choreo.synapse.executor.impl.OasGenerationExecutor.generateOasFile(OasGenerationExecutor.java:205)
[builder] 	at com.wso2.choreo.synapse.executor.impl.OasGenerationExecutor.execute(OasGenerationExecutor.java:138)
[builder] 	at com.wso2.choreo.synapse.SynapseResourceGenerator.main(SynapseResourceGenerator.java:30)

```

**Comment by arunans23** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/2160
