### ISSUE TITLE
NPE is observing when the MI instance starts up containing a data service with Boxcarring

### ISSUE THREAD

**Issue by LayaniMal** [wso2/micro-integrator#3292]
### Description
MI dashboard is not able to connect/control an MI instance if the MI instance starts up containing a data service with Boxcarring.

### Steps to Reproduce

- Create a Data Service that enables the Boxcarring. 
- Deploy the Car application( [BoxcarringCompositeExporter_1.0.0.zip](https://github.com/wso2/api-manager/files/14615365/BoxcarringCompositeExporter_1.0.0.zip) ) and observe the NPE.

### Affected Component

MI

### Version

4.1.0

### Relevant Log Output

```shell
[2024-03-15 17:38:24,484] ERROR {DataServiceResource} - Error while populating service: java.lang.NullPointerException
	at org.wso2.micro.integrator.dataservices.core.description.query.QuerySerializer.serializeAdvancedProps(QuerySerializer.java:109)
	at org.wso2.micro.integrator.dataservices.core.description.query.QuerySerializer.serializeQuery(QuerySerializer.java:85)
	at org.wso2.micro.integrator.dataservices.core.engine.DataServiceSerializer.serializeDataService(DataServiceSerializer.java:93)
	at org.wso2.micro.integrator.management.apis.DataServiceResource.populateDataServiceByName(DataServiceResource.java:153)
	at org.wso2.micro.integrator.management.apis.DataServiceResource.invoke(DataServiceResource.java:81)
	at org.wso2.carbon.inbound.endpoint.internal.http.api.InternalAPIDispatcher.dispatch(InternalAPIDispatcher.java:87)
	at org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpServerWorker.run(InboundHttpServerWorker.java:114)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Suggested Labels

MI-4.1.0

**Comment by chanikag** [comment]
Fixed with https://github.com/wso2/product-integrator-mi/pull/2713
