### ISSUE TITLE
Generate Swagger document for an API cannot be done in micro integrator

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#341]
**Description:**
When try to generate swagger document as in [1], it gives following error,

[2019-06-21 14:10:14,718] [micro-integrator] ERROR - NativeWorkerPool Uncaught exception
java.lang.NullPointerException
	at org.wso2.carbon.mediation.transport.handlers.utils.RequestProcessorDispatcherUtil.isDispatchToApiGetProcessor(RequestProcessorDispatcherUtil.java:68)
	at org.wso2.carbon.mediation.transport.handlers.PassThroughNHttpGetProcessor.process(PassThroughNHttpGetProcessor.java:344)
	at org.apache.synapse.transport.passthru.ServerWorker.processHttpRequestUri(ServerWorker.java:713)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:139)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[1] https://docs.wso2.com/display/EI650/Working+with+APIs#WorkingwithAPIs-GeneratingSwaggerdocumentsfortheAPIs

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sdkottegoda** [comment]
This is resolved by defining the correct PassThroughNHttpGetProcessor, i.e. org.wso2.micro.integrator.transport.handlers.PassThroughNHttpGetProcessor in axis2.xml
