### ISSUE TITLE
Error while writing file into Azure File Share using File Connector

### ISSUE THREAD

**Issue by asithamadhushanka12** [wso2/micro-integrator#3417]
### Description

While connecting to the Azure File Share using the file connector, the following error was observed due to the username being bound to the domain name with a backslash, as shown below.

`Ex: domain\username`

```
[2024-07-09 15:54:24,464] ERROR {SMBConnectionFactory} - Error while validating the connection org.apache.commons.vfs2.FileSystemException: Could not establish connection to "asitham.file.core.windows.net".
	at org.apache.commons.vfs2.provider.smb2.Smb2ClientWrapper.setupClient(Smb2ClientWrapper.java:137)
	at org.apache.commons.vfs2.provider.smb2.Smb2ClientWrapper.<init>(Smb2ClientWrapper.java:72)
	at org.apache.commons.vfs2.provider.smb2.Smb2WrapperClientFactory.create(Smb2WrapperClientFactory.java:36)
	at org.apache.commons.vfs2.provider.smb2.Smb2FileSystem.<init>(Smb2FileSystem.java:49)
	at org.apache.commons.vfs2.provider.smb2.Smb2FileProvider.doCreateFileSystem(Smb2FileProvider.java:58)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.getFileSystem(AbstractOriginatingFileProvider.java:158)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:112)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:82)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:785)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:658)
	at org.wso2.carbon.connector.connection.SMBConnectionFactory.validateObject(SMBConnectionFactory.java:54)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1198)
	at org.wso2.carbon.connector.core.pool.ConnectionPool.borrowObject(ConnectionPool.java:143)
	at org.wso2.carbon.connector.core.connection.ConnectionHandler.getConnection(ConnectionHandler.java:120)
	at org.wso2.carbon.connector.utils.Utils.getFileSystemHandler(Utils.java:255)
	at org.wso2.carbon.connector.operations.WriteFile.connect(WriteFile.java:120)
	at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32)
	at org.apache.synapse.mediators.ext.ClassMediator.updateInstancePropertiesAndMediate(ClassMediator.java:178)
	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:110)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:72)
	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:136)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:170)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:93)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:110)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:72)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.api.Resource.process(Resource.java:342)
	at org.apache.synapse.api.API.process(API.java:477)
	at org.apache.synapse.api.AbstractApiHandler.apiProcess(AbstractApiHandler.java:93)
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:71)
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:90)
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:76)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:396)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:455)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:203)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
**Caused by: com.hierynomus.mssmb2.SMBApiException: STATUS_LOGON_FAILURE (0xc000006d): Authentication failed for 'localhost\username' using com.hierynomus.smbj.auth.NtlmAuthenticator**@670cd83b
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:144)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.setupSession(SMBSessionBuilder.java:142)
	at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSessionBuilder.java:109)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:202)
	at org.apache.commons.vfs2.provider.smb2.Smb2ClientWrapper.setupClient(Smb2ClientWrapper.java:117)
```

**Comment by malakaganga** [comment]
Fixed: https://github.com/wso2/wso2-commons-vfs/pull/117
