### ISSUE TITLE
[Bug]: Error when try to insert document using MongoDB Connector

### ISSUE THREAD

**Issue by KalinduGandara** [wso2/micro-integrator#3419]
### Description

When try to invoke insertmany and find oparation it give this error.

`ERROR {MongoUtils} - Error occurred while inserting the documents to the database. org.bson.json.JsonParseException: JSON reader was expecting a value but found 'json'.
	at org.bson.json.JsonReader.readBsonType(JsonReader.java:243)
	at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:682)
	at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:724)
	at org.bson.AbstractBsonReader.readStartArray(AbstractBsonReader.java:445)
	at org.bson.codecs.BsonArrayCodec.decode(BsonArrayCodec.java:63)
	at org.bson.BsonArray.parse(BsonArray.java:66)
	at org.wso2.carbon.connector.operations.InsertMany.stringToDocumentList(InsertMany.java:63)
	at org.wso2.carbon.connector.operations.InsertMany.connect(InsertMany.java:98)
	at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32)
	at org.apache.synapse.mediators.ext.ClassMediator.updateInstancePropertiesAndMediate(ClassMediator.java:178)
	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:126)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:74)
	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:136)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:170)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:93)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:126)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:74)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.api.Resource.process(Resource.java:342)
	at org.apache.synapse.api.API.process(API.java:477)
	at org.apache.synapse.api.AbstractApiHandler.apiProcess(AbstractApiHandler.java:94)
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:72)
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:90)
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:76)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:350)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:399)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:458)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:206)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`
	
`ERROR {MongoUtils} - Error occurred while searching for the documents in the database. org.bson.json.JsonParseException: JSON reader was expecting a value but found 'json'.
	at org.bson.json.JsonReader.readBsonType(JsonReader.java:243)
	at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:682)
	at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:724)
	at org.bson.AbstractBsonReader.readStartDocument(AbstractBsonReader.java:452)
	at org.bson.codecs.DocumentCodec.decode(DocumentCodec.java:148)
	at org.bson.codecs.DocumentCodec.decode(DocumentCodec.java:45)
	at org.bson.Document.parse(Document.java:105)
	at org.bson.Document.parse(Document.java:90)
	at org.wso2.carbon.connector.operations.Find.connect(Find.java:77)
	at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32)
	at org.apache.synapse.mediators.ext.ClassMediator.updateInstancePropertiesAndMediate(ClassMediator.java:178)
	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:126)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:74)
	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:136)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:170)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:93)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:126)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:74)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.api.Resource.process(Resource.java:342)
	at org.apache.synapse.api.API.process(API.java:477)
	at org.apache.synapse.api.AbstractApiHandler.apiProcess(AbstractApiHandler.java:94)
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:72)
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:90)
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:76)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:350)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:399)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:458)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:206)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`

### Steps to Reproduce

1. Follow this and set up MongoDB Connextor - https://mi.docs.wso2.com/en/4.3.0/reference/connectors/mongodb-connector/mongodb-connector-example/
2. Try Testing on above document.

**Comment by KalinduGandara** [comment]
Error was due to missing field on document https://mi.docs.wso2.com/en/4.3.0/reference/connectors/mongodb-connector/mongodb-connector-example/
