### ISSUE TITLE
[Bug]: Query failed with error code 352 and error message 'Unsupported OP_QUERY command: find #5

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/micro-integrator#3503]
### Description

Moving the issue from https://github.com/wso2-extensions/esb-connector-mongodb/issues/5

![image](https://github.com/user-attachments/assets/1efa91c5-7a7f-407c-a32d-7f8b7be835b8)

**Description:**
We have configured MongoDB 6.0.3 correctly, but the connector fails when we launch the find operation:

[2023-02-10 16:46:44,279] ERROR {MongoUtils} - Error occurred while searching for the documents in the database. com.mongodb.MongoQueryException: Query failed with error code 352 and error message 'Unsupported OP_QUERY command: find. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal' on server localhost:27017

Is there any other solution except downgrading MongoDB?

**Affected Product Version:**
esb-connector-mongodb

**Related Issues:**
[2023-02-10 16:46:44,279] ERROR {MongoUtils} - Error occurred while searching for the documents in the database. com.mongodb.MongoQueryException: Query failed with error code 352 and error message 'Unsupported OP_QUERY command: find. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal' on server localhost:27017
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:720)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:709)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:433)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:406)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:709)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:81)
	at com.mongodb.Mongo.execute(Mongo.java:810)
	at com.mongodb.Mongo$2.execute(Mongo.java:797)
	at com.mongodb.OperationIterable.iterator(OperationIterable.java:47)
	at com.mongodb.FindIterableImpl.iterator(FindIterableImpl.java:200)
	at org.wso2.carbon.connector.utils.SimpleMongoClient.findDocuments(SimpleMongoClient.java:173)
	at org.wso2.carbon.connector.operations.Find.connect(Find.java:84)
	at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32)
	at org.apache.synapse.mediators.ext.ClassMediator.updateInstancePropertiesAndMediate(ClassMediator.java:178)
	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:97)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:110)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:72)
	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:136)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:170)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:93)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:110)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:72)
	at org.apache.synapse.config.xml.AnonymousListMediator.mediate(AnonymousListMediator.java:37)
	at org.apache.synapse.config.xml.SwitchCase.mediate(SwitchCase.java:69)
	at org.apache.synapse.mediators.filters.SwitchMediator.mediate(SwitchMediator.java:134)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:110)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:72)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.api.Resource.process(Resource.java:342)
	at org.apache.synapse.api.API.process(API.java:477)
	at org.apache.synapse.api.AbstractApiHandler.apiProcess(AbstractApiHandler.java:93)
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:71)
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:90)
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:76)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:101)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:376)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:435)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:183)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by chanikag** [comment]
This is fixed. https://github.com/wso2-extensions/esb-connector-mongodb/commit/0c692f812f90b71743dad6d3edb6a50f0b39feb3
