### ISSUE TITLE
NullPointerException is thrown when invoking a WS secured proxy

### ISSUE THREAD

**Issue by Vathsan** [wso2/micro-integrator#630]
**Description:**
The following exception is thrown when invoking a proxy service that is secured by WS Security policy (username token authentication) when the server is configured to use a JDBC user store.
```
java.lang.NullPointerException
	at org.wso2.carbon.user.core.util.UserCoreUtil.getDomainName(UserCoreUtil.java:571)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getMyDomainName(AbstractUserStoreManager.java:6073)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserStoreInternal(AbstractUserStoreManager.java:4876)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.access$400(AbstractUserStoreManager.java:86)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$7.run(AbstractUserStoreManager.java:4823)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$7.run(AbstractUserStoreManager.java:4820)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserStore(AbstractUserStoreManager.java:4820)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.authenticateInternal(AbstractUserStoreManager.java:583)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.access$100(AbstractUserStoreManager.java:86)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$4.run(AbstractUserStoreManager.java:540)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$4.run(AbstractUserStoreManager.java:537)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.authenticate(AbstractUserStoreManager.java:537)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$3.run(AbstractUserStoreManager.java:520)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$3.run(AbstractUserStoreManager.java:512)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.authenticate(AbstractUserStoreManager.java:512)
	at org.wso2.carbon.micro.integrator.security.callback.AbstractPasswordCallback.authenticateUser(AbstractPasswordCallback.java:165)
	at org.wso2.carbon.micro.integrator.security.callback.AbstractPasswordCallback.handle(AbstractPasswordCallback.java:78)
	at org.apache.rampart.TokenCallbackHandler.handle(TokenCallbackHandler.java:118)
	at org.apache.ws.security.processor.UsernameTokenProcessor.handleUsernameToken(UsernameTokenProcessor.java:168)
	at org.apache.ws.security.processor.UsernameTokenProcessor.handleToken(UsernameTokenProcessor.java:61)
	at org.apache.ws.security.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:371)
	at org.apache.ws.security.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:287)
	at org.apache.ws.security.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:236)
	at org.apache.rampart.RampartEngine.process(RampartEngine.java:227)
	at org.apache.rampart.handler.RampartReceiver.invoke(RampartReceiver.java:93)
	at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
	at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
	at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:261)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:167)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:415)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:152)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Suggested Labels:**
BUG

**Affected Product Version:**
MI 1.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Create a JDBC user store and configure it in MI (user-mgt.xml)
2. Create proxy service and secure it with WS security policy (username token authentication) as mentioned in [1] with the user details configured in JDBC user store
3. Deploy the car file in MI
4. Invoke the proxy service using Soap UI

**Related Issues:**
#486 

[1] https://docs.wso2.com/display/EI650/Applying+Security+to+a+Proxy+Service

**Comment by Vathsan** [comment]
Closing this issue, as the proxy service secured with WS security policy (username token authentication) is working in a 
MI 1.2.0-beta pack.
