### ISSUE TITLE
ConfigurationContext is not set when deploying artifacts using a CAPP

### ISSUE THREAD

**Issue by sachithKay** [wso2/micro-integrator#755]
**Description:**
Following error is thrown when invoking the management api after deploying a CAPP in MI.

```
Exception occurred when running org.wso2.micro.integrator.inbound.endpoint.protocol.http.InboundHttpServerWorker java.lang.NullPointerException
	at org.wso2.micro.integrator.transport.handlers.PassThroughNHttpGetProcessor.process(PassThroughNHttpGetProcessor.java:241)
	at org.apache.synapse.transport.passthru.ServerWorker.processHttpRequestUri(ServerWorker.java:713)
	at org.wso2.micro.integrator.inbound.endpoint.protocol.http.InboundHttpServerWorker.run(InboundHttpServerWorker.java:100)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

init method in PassThroughNHttpGetProcessor is not invoked when a CAPP is deployed at server startup hence Configuration context is null.

**Comment by Nirothipan** [comment]
This issue is not reproducible.
