### ISSUE TITLE
[CLI] - Issue in log-level command

### ISSUE THREAD

**Issue by RidmiR** [wso2/micro-integrator#980]
**Description:**

Error throwing when running log-level command in CLI. 
**_mi log-level show org.apache.log4j.ConsoleAppender_**

[2019-10-02 14:44:52,432] ERROR {org.wso2.micro.integrator.inbound.endpoint.protocol.http.InboundHttpServerWorker} - Exception occurred when running org.wso2.micro.integrator.inbound.endpoint.protocol.http.InboundHttpServerWorker java.lang.UnsupportedOperationException: Operation not supported in pax-logging
	at org.apache.log4j.LogManager.exists(LogManager.java:157)
	at org.wso2.micro.integrator.management.apis.LoggingResource.getLoggerData(LoggingResource.java:156)
	at org.wso2.micro.integrator.management.apis.LoggingResource.invoke(LoggingResource.java:72)
	at org.wso2.micro.integrator.inbound.endpoint.internal.http.api.InternalAPIDispatcher.dispatch(InternalAPIDispatcher.java:82)
	at org.wso2.micro.integrator.inbound.endpoint.protocol.http.InboundHttpServerWorker.run(InboundHttpServerWorker.java:111)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Affected Product Version:**
MI- 1.1.0

**Comment by Nirothipan** [comment]
As the implementation is now in log4j2 , we might have to update the CLI.
